iqlusioninc/crates

- .circleci/config.yml
- Dockerfile
I haven't found a good way to use `scl-source enable` inside of Docker, but this should mimick the effect and eliminate the need to manually enable SCL.
> Dockerfile: enable SCL packages in Docker environment

- rpmlib/Cargo.toml
- rpmlib/src/lib.rs
- rpmlib/src/txnset.rs
Initial support for creating transaction sets (with implicit `Drop`-based destructor)
> rpmlib: Basic wrapper for rpmts

- .circleci/config.yml
- Dockerfile
These flags enable the `core::arch` AES-NI instructions on x86-64 CPUs.
> Dockerfile: Set RUSTFLAGS

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- README.md
- canonical-path/Cargo.toml
- canonical-path/README.md
- canonical-path/src/lib.rs
A crate which provides `CanonicalPath` and `CanonicalPathBuf` types which can be used in situations where we want to avoid symlink-related issues/trickery.
> Initial canonical-path crate

- .circleci/config.yml
- rpmlib-sys/Cargo.toml
- rpmlib-sys/build.rs
- rpmlib-sys/include/rpmbuild.hpp
- rpmlib-sys/include/rpmlib.hpp
- rpmlib-sys/include/rpmsign.hpp
- rpmlib-sys/src/lib.rs
- rpmlib/src/txnset.rs
It's unlikely anyone will actually use either of these in the near future, but it's also nice we're successfully generating bindings for them.
Gate both of them on optional cargo features which have to be opted into. That way we don't waste time running bindgen on them unless people actually care, but in CI we can ensure we can still produce bindings for them.
> rpmlib-sys: Use cargo features to control binding/linking rpmbuild + rpmsign

- rpmlib/src/config.rs
- rpmlib/src/global_state.rs
- rpmlib/src/lib.rs
Adds a static mutex-locked struct for tracking rpmlib's global mutable state
> rpmlib: Track mutable global state in GlobalState struct

- Cargo.lock
- Cargo.toml
- cargo-rpm/.rpm/cargo-rpm.spec
- cargo-rpm/Cargo.toml
- cargo-rpm/src/cargo_config.rs
- cargo-rpm/src/init.rs
- cargo-rpm/src/license.rs
- cargo-rpm/src/main.rs
- cargo-rpm/src/shell.rs
- cargo-rpm/src/target.rs
- cargo-rpm/src/templates.rs
- cargo-rpm/templates/README.md
- cargo-rpm/templates/service.hbs
- cargo-rpm/templates/spec.hbs
- iq-cli/src/lib.rs
- iq-cli/src/shell.rs
Adds a "cargo rpm" subcommand which builds RPM releases of Rust projects.
Well... not just yet, but "cargo rpm build" will do that, and this PR was already getting pretty unwieldy.
In an act of inception, this project is already "cargo rpm init"-ed.
> cargo-rpm: Initial crate with "cargo rpm init" command

- AUTHORS.md
- cargo-rpm/src/target.rs
Simple change, and makes cargo-rpm match cargo's own behavior.
> Respect the CARGO_TARGET_DIR environment var, if set

- Cargo.lock
- iq-cli/Cargo.toml
- iq-cli/src/lib.rs
- iq-cli/src/macros/log.rs
- iq-cli/src/macros/mod.rs
This is a bit hax: it uses the macros directly from the upstream crate rather than a more elegant way of re-exporting them.
Doing it better seems blocked on this issue, which isn't likely to happen:
https://github.com/rust-lang/rust/issues/29638
> iq-cli: Re-export the log crate and macros

- iq-cli/src/macros/mod.rs
- iq-cli/src/macros/options.rs
This is a spike which attempts to emulate the behavior of `clap` when parsing command-line arguments.
It's presently implemented as a bunch of `macro_rules`, however really it should be implemented as proper functions in conjunction with `derive(Options)`.
> iq-cli: Add (hax) macro_rules for command-line option handling

- iq-cli/src/init.rs
- iq-cli/src/lib.rs
Moves all framework configuration to a struct, and makes `iq_cli::init` take `Into<InitOpts>` as an argument.
This allows commands to `impl Into<InitOpts>` so that `InitOpts` can be created from given command-line options easily.
> iq-cli: New init() API with InitOpts

- README.md
It's been moved into its own repository:
https://github.com/iqlusioninc/abscissa/
> README.md: Remove Abscissa

- Cargo.lock
- Cargo.toml
- zeroize/Cargo.toml
- zeroize/LICENSE-MIT
- zeroize/README.md
- zeroize/build.rs
- zeroize/src/lib.rs
- zeroize/src/nightly.rs
- zeroize/src/os/linux/explicit_bzero_backport.c
- zeroize/src/os/windows/explicit_bzero_shim.c
- zeroize/src/stable/explicit_bzero.rs
- zeroize/src/stable/explicit_memset.rs
- zeroize/src/stable/memset_s.rs
- zeroize/src/stable/mod.rs
Rust crate for securely zeroing memory while avoiding compiler optimizations.
Yes, there are already a dozen crates for doing this, however they are all (according to my accounting) "best effort" and fall back to using tricks to attempt to outsmart the compiler.
This crate exclusively wraps secure intrinsics and does not provide any sort of insecure fallback. If a suitable OS or Rust intrinsic is not available, it will fail to compile.
> zeroize: Initial crate

- Cargo.lock
- Cargo.toml
- README.md
- subtle-encoding/Cargo.toml
- subtle-encoding/LICENSE-MIT
- subtle-encoding/README.md
- subtle-encoding/src/base64.rs
- subtle-encoding/src/encoding.rs
- subtle-encoding/src/error.rs
- subtle-encoding/src/hex.rs
- subtle-encoding/src/identity.rs
- subtle-encoding/src/lib.rs
- subtle-encoding/src/macros.rs
- subtle-encoding/src/prelude.rs
Encoders and decoders for common data encodings (WIP) which avoid branching or performing table lookups based on their inputs (a.k.a. constant time-ish).
Useful for encoding/decoding secret values such as cryptographic keys.
> subtle-encoding: Initial crate

- AUTHORS.md
- zeroize/README.md
The proper name for the operating system is now macOS rather
than Mac OS X. I guess it is for parity with iOS, watchOS and tvOS.
> Update macOS name in README

- Cargo.lock
- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize/src/zeroize.rs
Adds a trait for clearing types in a secure fashion, and impls it for `T: AsMut<[u8]>`, with the idea that it can be implemented for custom types (and potentially other types by default).
> zeroize: Add 'Zeroize' trait

- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize/src/nightly.rs
- zeroize/src/stable/explicit_bzero.rs
- zeroize/src/stable/explicit_memset.rs
- zeroize/src/stable/memset_s.rs
- zeroize/src/stable/mod.rs
- zeroize/src/zeroize.rs
This commit makes the `secure_zero_memory()` function `pub(crate)` and uses it to implement the `Zeroize` trait for `AsMut<[u8]>`, which is now the only API provided by this crate.
It might be worth adding back for certain cases(?), but this crate's original focus was having a very simple API, and with both there's confusion as to which to use.
Removing `secure_zero_memory()` from the public API makes it *very* clear: `Zeroize` is the API to use.
> zeroize: Replace 'secure_zero_memory' with 'Zeroize'

- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize/src/zeroize.rs
A blanket impl on `AsMut<[u8]>` turns out to be pretty limiting in practice. This changes it to a set of impls on concrete types, particularly ones we might use to store secret data.
TODO: integers
> zeroize: Impl 'Zeroize' trait on concrete types

- .travis.yml
- gaunt/Cargo.toml
- gaunt/README.md
- gaunt/src/connection.rs
- gaunt/src/error.rs
- gaunt/src/lib.rs
- gaunt/src/path.rs
- gaunt/src/prelude.rs
- gaunt/src/response.rs
Gate parts of the crate which can build on `no_std` versus with the `alloc` feature versus which ones have hard dependencies on `std`.
Most things need at least `alloc` to do anything useful, but this should be expandable after switching to the `no_std`-friendly `httparse` crate.
> gaunt: Initial support for a no_std profile

- Cargo.lock
- gaunt/src/connection.rs
- gaunt/src/lib.rs
- gaunt/src/request.rs
- gaunt/src/response/body.rs
- gaunt/src/response/mod.rs
- gaunt/src/response/reader.rs
Gaunt's initial implementation was a purpose-specific hack.
This commit contains initial work to better generalize Gaunt's implementation, add types for concepts we'll need to build out in the future, and otherwise clean up bad interfaces/hacks in preparation for
retrofitting `httparse` as the HTTP parser.
> gaunt: Refactor in prep for 'httparse'

- Cargo.lock
- gaunt/CHANGES.md
- gaunt/Cargo.toml
- gaunt/src/lib.rs
- Refactor in prep for switching to `httparse` (#124)
- Initial `no_std` profile support (#121)
- Use `slog` for logging (#119)
> gaunt v0.1.0

- subtle-encoding/src/encoding.rs
The call to invoke the actual encoding/decoding functions was unintentionally gated on a `debug_assert_eq!`, and therefore was never invoked in release builds, resulting in all zeroes for encode/decode operations.
This change moves these invocations outside of the `debug_assert_eq!` statements so they are invoked in release builds.
> subtle-encoding: Fix encode/decode in release builds

- Cargo.toml
The `overflow-checks = true` option enables panic-on-overflow semantics, and we're not using `panic = abort`, so this comment should say "panic".
> Cargo.toml: Fix comment (s/abort/panic/)

- .travis.yml
PR #126 to the `subtle-encoding` crate fixed a critical bug which only occurred in release builds. Testing in release mode would've prevented it.
This commit changes CI tests to run in release mode to catch this sort of thing.
> .travis.yml: Test all crates in release mode

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Fix critical encode/decode bug in `release` builds (#126)
- Non-constant-time Bech32 implementation via `bech32-preview` feature (#113)
> subtle-encoding v0.3.0

- AUTHORS.md
- zeroize/Cargo.toml
- zeroize/build.rs
I changed `get_glibc_version` so that when the return code is not 0 it will check if it is a musl dynamic loader first before it panics, if that's the case it returns a version less than the least known glibc version that supported `explicit_bzero` to force compilation of the backport.
> [zeroize] Support musl-libc

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
> zeroize v0.4.1

- zeroize/build.rs
Older versions do not contain the string "glibc" but instead have e.g.:
ldd (GNU libc) 2.17
> zeroize: Fix ldd scraper for older glibc versions

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Fix ldd scraper for older glibc versions (#134)
> zeroize v0.4.2

- .travis.yml
They are now stable as of Rust 1.31
> Remove *-preview from rustup components

- zeroize/Cargo.toml
- zeroize/src/lib.rs
Adds `Zeroize` impls for `Vec` and `String` gated on an `alloc` feature (available automatically on `nightly`, but requiring `std` on stable).
For both of these types, the `clear()` method is called to make them zero-length.
> zeroize: Impls for Vec and String

- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
Avoids repeatedly calling the `Z::default()` function.
> zeroize: Documentation improvements and small code cleanups

- canonical-path/Cargo.toml
- gaunt/Cargo.toml
- subtle-encoding/Cargo.toml
- tai64/Cargo.toml
or: there and back again.
We've migrated back to Travis CI as it allows for testing of Linux, Mac, and Windows on a single CI environment and without the need to manage a Docker image.
> Cargo.toml (all crates): circle-ci -> travis-ci

- Cargo.lock
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
This release is a rewrite which replaces FFI bindings to OS-specific APIs with a pure Rust solution.
- Use `core::sync::atomic` fences (#146)
- Test wasm target (#143)
- Rewrite using `core::ptr::write_volatile` (#142)
> zeroize v0.5.0

- tai64/src/lib.rs
On Windows, `SystemTime` is a copy type, so passing it by ref fails this clippy lint.
This crate is already 1.0, and this is not true on other platforms, so allow pass-by-ref on the one function where this occurs.
For background, see https://travis-ci.org/iqlusioninc/crates/jobs/471506875#L202
> tai64: Ignore clippy pass-by-ref lint for SystemTime on Windows

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Add `debug_assert!` to ensure string interiors are zeroized (#156)
> zeroize v0.5.2

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Fix `#![no_std]` support (#158)
> subtle-encoding v0.3.2

- subtle-encoding/src/base64.rs
- subtle-encoding/src/bech32/base32.rs
- subtle-encoding/src/bech32/mod.rs
- subtle-encoding/src/error.rs
- subtle-encoding/src/hex.rs
The length calculations we presently perform are dependent on whitespace-free inputs.
This adds an (unfortunately non-constant time) check that the *last* character is *NOT* whitespace. Ideally this would be replaced with a constant time "trim" function that can slice away leading/trailing
whitespace, but for now this gives a meaningful error.
It also adds checks that buffers are correctly sized to receive the resulting output, where otherwise it would've panicked for an undersize buffer. This is a potential DoS vector if subtle-encoding was used on untrusted inputs.
> Return errors for undersize decode buffers and trailing whitespace

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Return errors for undersize decode buffers and trailing whitespace (#163)
> subtle-encoding v0.3.3

- Cargo.lock
- Cargo.toml
- README.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
- zeroize_derive/LICENSE-MIT
- zeroize_derive/README.md
- zeroize_derive/src/lib.rs
Adds a `zeroize_derive` crate, re-exported through `zeroize` (and gated on an optional but on-by-default cargo feature).
Presently limited to structs.
> zeroize_derive: Custom derive support for Zeroize

- zeroize/src/lib.rs
- zeroize_derive/src/lib.rs
Adds support for deriving the `ZeroizeOnDrop` trait, which invokes `zeroize()` on `self` inside of the `Drop` handler.
> zeroize: Add ZeroizeOnDrop marker trait + custom derive

- Cargo.lock
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/README.md
- Add ZeroizeOnDrop marker trait + custom derive (#168)
- Custom derive support for `Zeroize` (#167)
- Rename `ZeroizeWithDefault` to `DefaultIsZeroes` (#166)
> zeroize v0.6.0

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- `zeroize` v0.6.0 (#170)
- Make internals of Bech32 type private (#165)
> subtle-encoding v0.3.4

- Cargo.lock
- tendermint-rpc/Cargo.toml
- tendermint-rpc/src/endpoints.rs
- tendermint-rpc/src/endpoints/status.rs
- tendermint-rpc/src/jsonrpc.rs
- tendermint-rpc/src/lib.rs
- tendermint-rpc/tests/endpoints.rs
- tendermint-rpc/tests/integration.rs
Uses `gaunt` for now for simplicity.
Should probably switch over to `hyper` (or a `gaunt`-wrapped `hyper`) in the future for better performance.
> tendermint-rpc: Basic JSONRPC/HTTP support + integration test

- zeroize/src/lib.rs
Fixes #178.
I added a test which uses `set_len` to observe that data has been zero'd.
I feel that this is useful, as it tests my code change, but it in no way tests the actual (post-optimisation) functionality of the library. I'm happy for it to be dropped, if someone else hates it. It is probably not guaranteed to pass, or even be safe (i.e. if `clear()` is changed to deallocate the storage).
> zeroize Vec's capacity() by extending

- Cargo.lock
- zeroize/src/lib.rs
Adds a convenience wrapper type `Zeroizing<Z: Zeroize>` which can wrap any zeroizable value and then call `zeroize()` on it in the `Drop` impl.
This avoids the need to define a newtype for every value intended to be zeroized on drop.
> zeroize: Add Zeroizing<Z> to zeroize values on drop

- .travis.yml
- AUTHORS.md
- CONTRIBUTING.md
- README.md
- appveyor.yml
- canonical-path/Cargo.toml
- canonical-path/README.md
- gaunt/Cargo.toml
- gaunt/README.md
- subtle-encoding/Cargo.toml
- subtle-encoding/README.md
- tai64/Cargo.toml
- tai64/README.md
- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
- zeroize_derive/README.md
Zeroize previously provided a 'nightly' feature which used a slightly more complex implementation in order to facilitate a micro-optimization: namely it used [volatile_set_memory] on `nightly` to efficiently byte slices (which typically thunks to `memset()` followed by a fence instruction).
However, the extra complexity was never justified through benchmarking, nor does it represent the desired path forward on nightly (which would be to use atomic writes instead of volatile writes, when they become available but aren't yet stabilized).
It also seems some `Zeroize` impls are missing, particularly for arrays, in which case the special-case nightly impls become more cumbersome.
This commit rips out the entire nightly feature and ensures the crate behaves the same way everywhere regardless of …
> zeroize: Remove 'nightly' feature

- Cargo.lock
- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
- zeroize_derive/Cargo.toml
- zeroize_derive/src/lib.rs
Replaces the previous handrolled proc macros with ones generated by synstructure.
This not only makes them more declarative and maintainable, but also allows testing that the output of the proc macro generates the desired code.
> zeroize_derive: Use synstructure

- .travis.yml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
- zeroize_derive/src/lib.rs
This change replaces the `ZeroizeOnDrop` trait by having the custom derive for `Zeroize` automatically impl `Drop` and call `zeroize()`.
Opt-out of the default `Drop` handler is provided in the form of a custom attribute: `#[zeroize(no_drop)]`.
This should make zeroizing-on-drop the "happy path" for this crate.
> zeroize_derive: Impl Drop by default when deriving Zeroize

- README.md
- canonical-path/README.md
- gaunt/README.md
- subtle-encoding/README.md
- tai64/README.md
Shows minimum supported version.
Some are labeled as 1.31 and others 1.34. The plan is to do another release of "passively-maintained" crates, and then bump all of them to 1.34 (as that's the minimum we presently test on).
> Add rustc badges to all crates

- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
Updates the 'alloc'-related boilerplate to support usage with the recently stabilized Rust feature.
> zeroize: Support stablized 'alloc' crate

- Cargo.lock
- canonical-path/CHANGES.md
- canonical-path/Cargo.toml
- canonical-path/src/lib.rs
- Clean up and modernize (#193)
- Update to 2018 edition (#138)
> canonical-path v2.0.0

- Cargo.lock
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/README.md
- tai64/src/lib.rs
NOTE: These changes bump the minimum Rust version to 1.34.0
- `to_external` and `from_external` replaced with `From`/`TryFrom`
- `byteorder` crate replaced with `from_be_bytes` / `to_be_bytes`
- `Error` type
- Update `quickcheck` to `0.8`
> tai64: Cleanups and modernization

- Cargo.lock
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/src/lib.rs
- `no_std` support (#196)
- Cleanups and modernization (#195)
- `to_external` and `from_external` replaced with `From`/`TryFrom`
- `byteorder` crate replaced with `from_be_bytes` / `to_be_bytes`
- `Error` type
- Update `quickcheck` to `0.8`
- Update to Rust 2018 edition (#138)
> tai64 v2.0.0

- canonical-path/src/lib.rs
Previously it returned an error if the input path were non-canonical.
This changes it to actively canonicalize the path before returning.
> canonical-path: Canonicalize 'current_exe()'

- canonical-path/README.md
- gaunt/README.md
- secrecy/Cargo.toml
- secrecy/README.md
- tai64/README.md
Some crates in this repo are Apache 2.0 ONLY. Others are Apache 2.0+MIT.
Some of the previous boilerplate didn't properly reflect the intended licensing on these crates. This commit updates all licensing boilerplate to properly reflect our intent.
To spell it out explicitly:
- `canonical-path`
- `gaunt`
- `secrecy`
- `tai64`
- `subtle-encoding`
- `zeroize`
- `zeroize_derive`
Note: The crates that are dual licensed as MIT were either adapted from code that was originally MIT licensed with Apache 2.0 dual licensing added with the original author's permission (`subtle-encoding`), or deliberately dual licensed from the start with the goal of potentially upstreaming the code to Rust projects (`zeroize` / `zeroize_derive`)
> Clarify licensing

- .travis.yml
- appveyor.yml
- canonical-path/README.md
- gaunt/README.md
- secrecy/README.md
- subtle-encoding/README.md
- tai64/README.md
- zeroize/README.md
- zeroize_derive/README.md
Notably `Box<Fn*>` was stabilized and is quite useful.
This consistently advertises the supported `rustc` version across all crates is 1.35.
This should, hopefully, represent a minimum version we'll be able to stick with for awhile.
> Test all crates on Rust 1.35.0 (and bump min version)

- secrecy/src/lib.rs
Adds a marker trait for secrets which are allowed to be cloned.
Ideally secrets aren't cloned all over the place, so in lieu of a blanket impl, this marker trait allows certain secrets to be cloned.
> secrecy: Add CloneableSecret marker trait

- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
- zeroize_derive/src/lib.rs
The previous version of `zeroize` (v0.8) automatically derived a `Drop` impl unless `zeroize(no_drop)` was passed explicitly.
This felt like the right thing to do at first, however it turns out there are a lot of cases in practice where it's undesirable to derive `Drop` by default, e.g. on any `Copy` type. This was encountered
in-practice retrofitting `zeroize` into the `curve25519-dalek` crate.
This changes the custom derive impl to require an explicit decision in the form of an attribute as to whether a `Drop` impl should be derived or not.
Going forward (i.e. in `zeroize` 1.0) deriving `Drop` will need to be explicitly declared as `zeroize(drop)`, and the need to explicitly specify `zeroize(no_drop)` can be removed, meaning no `Drop` impl will be derived by default. However, since …
> zeroize_derive: Require zeroize(drop) or zeroize(no_drop)

- zeroize/src/lib.rs
...instead of `DefaultIsZeroes`. This makes them much more useful for custom derive, although they may not use the most performant implementation.
Better performance can be achieved in the future by adding custom attributes that allow specifying a more performant implementation should be used in cases where it actually matters.
> zeroize: Bound blanket array impls on Zeroize

- zeroize/src/lib.rs
The documentation previously included a lengthy essay about potential caveats in what it can guarantee as mixed volatile/non-volatile writes were previously assumed to be undefined behavior due to language to that effect in the official documentation for `write_volatile`.
That language has subsequently been removed after discussion about the safety implications:
https://github.com/rust-lang/rust/pull/60972
Though generally it's not a good idea to mix volatile and non-volatile writes when using volatile accesses to communicate with e.g. memory mapped external devices, for the particular usage pattern in this crate, i.e. writing a zero-value, it can be considered well-defined.
> zeroize: Remove scary language about undefined behavior

- zeroize/src/lib.rs
Per @RalfJung:
https://github.com/iqlusioninc/crates/pull/214#discussion_r290488758
> AFAIK atomic fences only really prevent reordering of atomic accesses.
> Non-atomic accesses can still be reordered. The interaction of this
> with volatile accesses is entirely unclear -- technically, they are
> non-atomic, but in practice it seems unlikely that the compiler would
> perform such reorderings.
> [...]
> A compiler fence seems like a reasonable precaution and also helps
> make sure the side-effects happens near where the programmer might
> expect it, but a CPU fence to me sounds more like cargo cult.
> zeroize: Remove CPU fences

- Cargo.lock
- secrecy/Cargo.toml
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
**NOTICE**: This release changes the default behavior of `derive(Zeroize)` to no longer derive a `Drop` impl. If you wish to derive `Drop`, you must now explicitly add a `#[zeroize(drop)]` attribute on the type for which you are deriving `Zeroize`.
- Remove CPU fences (#216)
- Remove scary language about undefined behavior (#214)
- Bound blanket array impls on `Zeroize` instead of `DefaultIsZeroes` (#213)
- Require `zeroize(drop)` or `zeroize(no_drop)` attributes when deriving `Zeroize` (#212).
- Support stablized 'alloc' crate (#192)
> zeroize v0.9.0

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
> secrecy v0.2.1

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
> subtle-encoding v0.3.7

- zeroize/src/lib.rs
Adds a blanket impl for `Option<Z: Zeroize>`
> zeroize: impl Zeroize for Option

- .travis.yml
- Cargo.lock
- README.md
- appveyor.yml
- hkd32/Cargo.toml
- hkd32/README.md
- hkd32/src/lib.rs
Moves derivation to a reference-based `Path` type, and adds an owned equivalent owned `PathBuf` type with support for parsing derivation paths from strings.
> hkd32: Path and PathBuf types

- Cargo.lock
- README.md
- hkd32/Cargo.toml
- hkd32/README.md
- hkd32/src/lib.rs
Adds integrated support for deriving the HKD32 key hierarchy from a BIP39 Mnemonic phrase.
Uses the `tiny-bip39` crate, a (maintained) fork of the `bip39` crate.
> hkd32: Add built-in bip39::Mnemonic support

- Cargo.lock
- hkd32/Cargo.toml
- hkd32/src/key_material.rs
- hkd32/src/lib.rs
- hkd32/src/path.rs
- hkd32/src/pathbuf.rs
Support for encoding/decoding `KeyMaterial` to/from Bech32 with arbitrary human readable parts.
> hkd32: Add (optional) Bech32 encoding support

- zeroize/README.md
- zeroize/src/lib.rs
- zeroize_derive/src/lib.rs
The previous attribute parser used a hack where it would compare to the s-exp representation of zeroize attributes to determine of they are `drop` or `no_drop`. This was a bit of a hack that broke with a recent nightly, which removed the spaces surrounding the ident.
This commit rewrites the attribute parser to properly walk the attribute `syn::Meta` nodes in the AST until it arrives at a `syn::Ident` containing either `drop` or `no_drop`. All other AST nodes will result in a panic.
This relaxes the previous restriction that any `#[derive(Zeroize)]` MUST be annotated with either `drop` or `no_drop`. This was put in place because `zeroize` v0.9 switched from default drop to requiring an explicit attribute. However v0.8 was the only version with implict drop, and has been yanked for several …
> zeroize: Improved attribute parser (fixes #237)

- .travis.yml
- subtle-encoding/src/bech32/mod.rs
The old syntax is causing build failures on 1.37:
https://ci.appveyor.com/project/tony-iqlusion/crates/builds/26780395/job/9jgvr9rye0q6mlok
> subtle-encoding: Use new inclusive range syntax

- zeroize_derive/src/lib.rs
The `no_drop` attribute existed because the initial proc macro implicitly added a `Drop` impl unless instructed otherwise.
It turns out there are several legitimate reasons not to derive `Drop`, so this was reversed in v0.9, with `drop` or `no_drop` attributes mandatory to ensure everyone migrated and was not expecting an implicit `Drop` handler to be derived (this was further enforced by yanking v0.8
which was the only version with this behavior).
Now that everyone has migrated, `no_drop` no longer serves any purpose, so this deprecates it by printing a warning.
> zeroize_derive: Deprecate `#[zeroize(no_drop)]` attribute

- Cargo.lock
- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
- zeroize_derive/Cargo.toml
- zeroize_derive/src/lib.rs
Uses 1.0 versions of the core proc macro crates
> zeroize_derive: Use 1.0 proc-macro2, quote, and syn crates

- Cargo.lock
- gaunt/Cargo.toml
- gaunt/src/connection.rs
- gaunt/src/error.rs
- gaunt/src/lib.rs
- gaunt/src/path.rs
- gaunt/src/prelude.rs
- gaunt/src/request.rs
- gaunt/src/response/body.rs
- gaunt/src/response/reader.rs
- subtle-encoding/Cargo.toml
- subtle-encoding/README.md
- subtle-encoding/src/base64.rs
- subtle-encoding/src/bech32/base32.rs
- subtle-encoding/src/bech32/mod.rs
- subtle-encoding/src/encoding.rs
- subtle-encoding/src/error.rs
- subtle-encoding/src/hex.rs
- subtle-encoding/src/identity.rs
- subtle-encoding/src/lib.rs
- subtle-encoding/src/prelude.rs
- tai64/Cargo.toml
- tai64/src/lib.rs
These crates weren't getting much value out of `failure`, and the use of proc macros to generate what is effectively a match statement on enum variants which returns a string literal adds a lot to compile times.
Furthermore, `failure` is still using the non-1.0 proc macro crates. It seems there's upstream work to get this fixed[1], but since we're not really getting value out of the proc macros as-is, there's not much reason to bother.
[1]: https://github.com/rust-lang-nursery/failure/pull/319
> gaunt/subtle-encoding/tai64: Remove `failure`

- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize_derive/README.md
Previously the `std` feature gated `Zeroize` impls on `Box`, `String`, and `Vec`.
Now that the `alloc` crate is stable, if we go MSRV 1.36+, we can always source these types from there, and thereby eliminate the `std` feature.
> Remove `std` feature in favor of `alloc`; MSRV 1.36+

- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
Proc macros are a somewhat onerous dependency due to the amount of time it takes to compile crates like `syn`, and many will prefer explicit implementations to ones derived via proc macros.
This commit removes `zeroize_derive` from the default feature list.
> zeroize: Disable `zeroize_derive` feature by default

- Cargo.lock
- hkd32/Cargo.toml
- secrecy/Cargo.toml
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
- Disable `zeroize_derive` Cargo feature by default (#247)
- Remove `std` feature in favor of `alloc`; MSRV 1.36+ (#246)
- Deprecate `#[zeroize(no_drop)]` attribute (#244)
- Use 1.0 `proc-macro2`, `quote`, and `syn` crates (#242)
> zeroize v0.10.0

- Cargo.lock
- hkd32/Cargo.toml
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- Remove `failure` (#245)
- Use `alloc` for heap allocations; MSRV 1.36+ (#245)
> subtle-encoding v0.4.0

- Cargo.lock
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/README.md
- tai64/src/lib.rs
> tai64 v3.0.0

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- Vendor (simplified) BIP39 implementation from `tiny-bip39` (#251)
- `subtle-encoding` v0.4.0 (#249)
- `zeroize` v0.10.0 (#248)
> hkd32 v0.2.0

- hkd32/CHANGES.md
- secrecy/Cargo.toml
- secrecy/README.md
- secrecy/src/boxed.rs
- secrecy/src/lib.rs
- secrecy/src/string.rs
- secrecy/src/vec.rs
Adds impls and type aliases for `Secret` wrappers for `Box`, `String`, and `Vec`.
> secrecy: Add support for alloc types

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Add support for `alloc` types (#253)
- `zeroize` v0.10.0 (#248)
- Add a default impl for `DebugSecret` trait (#241)
> secrecy v0.3.0

- .travis.yml
- canonical-path/src/lib.rs
- gaunt/src/error.rs
- gaunt/src/lib.rs
- gaunt/src/path.rs
- hkd32/src/lib.rs
- hkd32/src/path.rs
- secrecy/src/lib.rs
- subtle-encoding/src/error.rs
- subtle-encoding/src/lib.rs
- tai64/src/lib.rs
- zeroize/src/lib.rs
- zeroize_derive/src/lib.rs
- Replace `deny` on `warnings` and `missing_docs` with CI `-D` flags
- Add `rust_2018_idioms` and `unused_lifetimes` to all crates
- Split out `rustfmt`, `clippy`, and `cargo audit` in CI matrix
> Improve lints and deny policy

- Cargo.lock
- secrecy/Cargo.toml
- secrecy/src/bytes.rs
As title,  otherwise a consumer that wants to use `SecretBytes` would have to newtype it. What do you think, @tony-iqlusion?
> secrecy: Allow SecretBytes to be Serialized/Deserialized with Serde

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Add `SerializableSecret` (#262)
- Add (optional) concrete `SecretBytes` type (#258, #259, #260, #261)
> secrecy v0.4.0

- secrecy/src/bytes.rs
- zeroize/src/lib.rs
Previously used `DefaultIsZeroes`, however this is only useful for primitive types, and can't support e.g. `Vec` of arrays.
> zeroize: Loosen `Vec` trait bounds for `Zeroize`

- zeroize/src/lib.rs
When the inner `Z` type impls any of these traits, they will also be impl'd for `Zeroizing`.
> zeroize: Derive `Clone`, `Debug, and `Eq` for `Zeroizing` (closes #266)

- zeroize/src/lib.rs
This changes the trait bounds for the `Zeroize` impl on `Vec<Z>` from:
```rust
Z: Clone + Default + Zeroize
```
to just:
```rust
Z: Zeroize
```
This is based on my experience trying to switch `curve25519-dalek` from `clear_on_drop` to `zeroize` in this PR:
https://github.com/dalek-cryptography/curve25519-dalek/pull/289
Notably there were several places I was unable to use `Zeroizing` in conjunction with `Vec` because it requires `Clone` and `Default` in order for the current safe impl of zeroizing the excess capacity in
`Vec`s. IMO this is an implementation detail leaking out which places undue burden on the user and reduces overall utility.
This is another way of saying: this change effectively reverts #180. I think we can eventually bring this functionality back using an `unsafe` impl …
> zeroize: Relax `Zeroize` trait bounds for `Vec`

- zeroize/Cargo.toml
- zeroize/src/bytes.rs
- zeroize/src/lib.rs
Since `bytes` isn't 1.0 yet and we'd like to reserve the right to either upgrade it to another 0.x version in the future, or upstream the implementation so we can remove the feature entirely, this changes the
feature name to `bytes-preview` and explicitly calls it out as not included in the SemVer guarantees for `zeroize`.
Ideally I think we can upstream it, especially after a 1.0 release of `zeroize` itself.
> zeroize: Rename `bytes` feature to `bytes-preview`

- Cargo.lock
- hkd32/Cargo.toml
- secrecy/Cargo.toml
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/README.md
- zeroize/src/lib.rs
- zeroize_derive/CHANGES.md
- zeroize_derive/Cargo.toml
- zeroize_derive/README.md
- Initial 1.0 release 🎉:shipit:
- zeroize_derive: Remove legacy `no_drop` attribute support (#278)
- Rename `bytes` feature to `bytes-preview` (#277)
- Further relax `Zeroize` trait bounds for `Vec` (#276)
- Derive `Clone`, `Debug`, and `Eq` for `Zeroizing` (#275)
> zeroize v1.0.0

- hkd32/Cargo.toml
- hkd32/src/lib.rs
- hkd32/src/mnemonic.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/src/mnemonic/seed.rs
- hkd32/tests/bip39_vectors.rs
Allows use of a simpler derivation without dependence on the `pbkdf2` crate for cases that don't require full BIP39 compatibility.
> hkd32: Split out `bip39` cargo feature

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- Split out `bip39` cargo feature (#280)
- Upgrade to `zeroize` v1.0.0 (#279)
> hkd32 v0.3.0

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Upgrade to `zeroize` v1.0.0 (#279)
> secrecy v0.5.0

- Cargo.lock
- tai64/Cargo.toml
- tai64/src/lib.rs
Adds serde serializers/deserializers which are simple thunks to the TAI64/TAI64N binary wire format.
> tai64: Add (optional) serde support

- .github/workflows/rust.yml
We claim we test on macOS (and used to). This was lost in the GitHub Actions migration.
> .github: Add macos-latest to the build matrix

- zeroize/src/lib.rs
Allows moving an owned `Z` into a `Zeroizing` wrapper using `From`/`Into`.
> zeroize: Add `From<Z: Zeroize>` impl for `Zeroizing<Z>`

- .github/workflows/rust.yml
- .github/workflows/security_audit.yml
Allows cron-based build and path-based restrictions on when it runs
> .github: split Security Audit into security_audit.yml

- zeroize/src/lib.rs
Fallible trait for representing cases where zeroization may or may not be possible.
Primarily useful for scenarios like reference counted data, where zeroization is only possible when the last reference is dropped.
> zeroize: Add `TryZeroize` trait.

- secrecy/src/string.rs
As title.
Is required to use `SecretString` to parse warp headers, context: https://github.com/interledger-rs/interledger-rs/pull/553#discussion_r354372766
> feat(SecretString): implement FromStr for SecretString

- secrecy/src/lib.rs
This PR adds `CloneableSecret` impls for arrays.
> secrecy: Add CloneableSecret impls for arrays

- Cargo.lock
- secrecy/Cargo.toml
- secrecy/src/bytes.rs
It's tricky with Rust's feature system to represent the combination of features in such a way that it can conditionally activate another feature of one of the crates when that crate is itself a feature.
This instead handles feature unification for `bytes` and `serde` through a not-too-terribly-compilicated custom deserializer such that merely having both features active is enough to receive the impl.
> secrecy: Replace `bytes-serde` feature with custom deserializer

- anomaly/README.md
- anomaly/src/macros.rs
...to avoid having to import them.
> anomaly: Use $crate when referencing nested macros

- Cargo.lock
- anomaly/CHANGES.md
- anomaly/Cargo.toml
- anomaly/src/lib.rs
- Use `$crate` when referencing nested macros (#319)
> anomaly v0.1.1

- secrecy/src/string.rs
`core::convert::Infallible` can ensure the user that the error will
never happen. Further `Infallible` implements all the usual traits which
means that it doesn’t impact normal error handling through string
conversion (such as the unit type does because it does not implement
`Display`).
> secrecy: use Infallible for FromStr for SecretString

- Cargo.lock
- Cargo.toml
- README.md
- hkd32/src/pathbuf.rs
- stdtx/Cargo.toml
- stdtx/README.md
- stdtx/src/address.rs
- stdtx/src/amino_types.rs
- stdtx/src/builder.rs
- stdtx/src/decimal.rs
- stdtx/src/error.rs
- stdtx/src/lib.rs
- stdtx/src/msg.rs
- stdtx/src/msg/builder.rs
- stdtx/src/msg/field.rs
- stdtx/src/msg/value.rs
- stdtx/src/schema.rs
- stdtx/src/schema/definition.rs
- stdtx/src/schema/field.rs
- stdtx/src/schema/value_type.rs
- stdtx/src/type_name.rs
- stdtx/tests/integration.rs
- stdtx/tests/support/example_schema.toml
Originally developed here as the `cosmos-stdtx` crate:
https://github.com/tendermint/kms/pull/401
This imports the code, renames it to the more convenient `stdtx` crate, and updates links and path references to other crates in this repo.
> stdtx: Initial crate

- AUTHORS.md
- zeroize/src/lib.rs
Re-implement #180, but without any additional required trait bounds, which is why #180 was reverted in  #276.
> zeroize: zeroize entire capacity of `Vec`

- Cargo.lock
- anomaly/Cargo.toml
- anomaly/README.md
- anomaly/src/context.rs
- anomaly/src/error.rs
- anomaly/src/lib.rs
Provides an `Error` type containing a `Box<Context<Kind>>` which is useful for propagating errors. It impls `Deref` to the underlying `Context`, and also `Display` and `std::error::Error`
Unfortunately, having `anomaly` define this type (rather than the end-user crate) means that the end-user crate can no longer impl `From` to do automatic error conversions to this type.
An alternative solution would be to have `anomaly` provide a proc macro which derives the set of traits the `Error` type impls, allowing each crate to define their own `Error` type, but have them behave in the same way.
However, for now, this is better than nothing.
> anomaly: Add generic `Error` type

- zeroize/src/lib.rs
This PR modifies the `Zeroize` implementation of `String` to zero the entire allocated capacity of a `String`. Previously only the initialized capacity was zeroed.
> zeroize: zeroize entire capacity of `String`

- .github/workflows/rust.yml
- Cargo.lock
- hkd32/Cargo.toml
- hkd32/src/key_material.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/src/mnemonic/seed.rs
- stdtx/Cargo.toml
Updates:
`ecdsa` => v0.6
`hmac` => v0.8
`pbkdf2` => v0.4
`sha2` => v0.9
`signatory-secp256k1`  => v0.20
> Update `ecdsa`, `hmac`, `pbkdf2`,`sha2`, `signatory-secp256k1`  dependencies 

- stdtx/src/builder.rs
- stdtx/src/lib.rs
- stdtx/src/schema.rs
Have `stdtx::Builder` borrow the signer with each signing request rather than owning it.
This is helpful in concurrent environments.
> stdtx: have stdtx::Builder borrow signer

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- Update `hmac` to v0.8 ([#435])
- Update `pbkdf2` to v0.4 ([#435])
- Update `sha2` to v0.9 ([#435])
[#435]: https://github.com/iqlusioninc/crates/pull/435
> hkd32 v0.4.0

- stdtx/src/amino_types.rs
- stdtx/src/builder.rs
Allows bidirectional (de)serialization, and eliminates the need for handwritten serializers using the `json!` macro.
> stdtx: use serde for StdFee serialization

- Cargo.lock
- stdtx/CHANGES.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- `StdTx::new` method ([#446])
- Derive `Copy` on `Address` ([#445])
- `Msg::from_json_value` ([#443])
- Impl `serde::Deserialize` for `Address` ([#439])
- Use serde for `StdFee` serialization ([#444])
- Have `stdtx::Builder` borrow signer ([#441])
- Update `ecdsa`, `sha2`, `signatory-secp256k1` dependencies  ([#435])
- Update `rust_decimal` to 1.6.0 ([#415])
- Update `anomaly` to 0.2.0 ([#354])
[#446]: https://github.com/iqlusioninc/crates/pull/446
[#445]: https://github.com/iqlusioninc/crates/pull/445
[#444]: https://github.com/iqlusioninc/crates/pull/444
[#443]: https://github.com/iqlusioninc/crates/pull/443
[#441]: https://github.com/iqlusioninc/crates/pull/441
[#439]: https://github.com/iqlusioninc/crates/pull/439
[#435]: https://github.com/iqlusioninc/crates/pull/435
[#415]: …
> stdtx v0.2.0

- Cargo.lock
- stdtx/CHANGES.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- Bump `prost-amino`/`prost-amino-derive` to v0.6 ([#451])
[#451]: https://github.com/iqlusioninc/crates/pull/451
> stdtx v0.2.1

- secrecy/src/lib.rs
NOTE: addresses #458
The `SerializableSecret` trait was added in #262, however the `Serialize` (as well as `Deserialize`) impls were (unintentionally) bounded on `DebugSecret`.
This commit removes the `DebugSecret` bound on the `Deserialize` impl, adds the intended `SerializableSecret` on the `Serialize` impl, and improves the documentation for the `SerializableSecret` trait.
> secrecy: use `SerializableSecret` in `Serialize` bounds

- secrecy/Cargo.toml
- secrecy/src/boxed.rs
- secrecy/src/bytes.rs
- secrecy/src/lib.rs
- secrecy/src/string.rs
- secrecy/src/vec.rs
Improves `rustdoc` documentation by notating types which are conditionally available based on cargo features.
> secrecy: add doc_cfg

- secrecy/src/lib.rs
Re-exports the `Zeroize` trait from the `zeroize` crate, along with the crate itself.
> secrecy: re-export zeroize

- secrecy/CHANGES.md
Also adds https://keepachangelog.com boilerplate (not applied retroactively, but to be used for future changelog updates)
> secrecy: reformat CHANGES.md

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Re-export zeroize ([#466])
- `rustdoc` improvements ([#464], [#465])
- Have `DebugSecret` take a formatter ([#467])
- Make `FromStr` impl for `SecretString` be `Infallible` ([#323])
- Use `SerializableSecret` in `Serialize` bounds ([#463])
[#467]: https://github.com/iqlusioninc/crates/pull/467
[#466]: https://github.com/iqlusioninc/crates/pull/466
[#465]: https://github.com/iqlusioninc/crates/pull/465
[#464]: https://github.com/iqlusioninc/crates/pull/464
[#463]: https://github.com/iqlusioninc/crates/pull/463
[#323]: https://github.com/iqlusioninc/crates/pull/323
> secrecy v0.7.0

- zeroize/src/lib.rs
Closes #474
Adds a `#[cfg(feature = "derive")]` to the `zeroize` doctests.
This allows the doctests to pass when the feature is disabled.
> zeroize: gate custom derive rustdoc on the `derive` feature

- anomaly/LICENSE-APACHE
- canonical-path/LICENSE
- harp/LICENSE
- hkd32/LICENSE-APACHE
- secrecy/LICENSE-APACHE
- stdtx/LICENSE
- subtle-encoding/LICENSE-APACHE
- tai64/LICENSE
- zeroize/LICENSE-APACHE
- zeroize_derive/LICENSE-APACHE
For crates licensed only Apache 2.0, copies the toplevel `LICENSE` into each crate's directory.
For dual licensed crates, copies it, but renamed to `LICENSE-APACHE`.
Closes #475
> Add license files to all crates

- zeroize/Cargo.toml
- zeroize/src/lib.rs
Intended to be rendered on https://docs.rs
> zeroize: add `doc_cfg`

- Cargo.lock
- stdtx/Cargo.toml
- stdtx/src/lib.rs
The `k256` crate is now capable of producing ECDSA signatures.
> stdtx: replace `signatory-secp256k1` with `k256`

- Cargo.lock
- subtle-encoding/src/error.rs
dep updates:
`backtrace` v0.3.51 -> v0.3.52
`chrono` v0.4.18 -> v0.4.19
`ecdsa` v0.8.3 -> v0.8.5
`elliptic-curve` v0.6.2 -> v0.6.6
`k256` v0.5.6 -> v0.5.9
`libc` v0.2.77 -> v0.2.79
`miniz_oxide` v0.4.2 -> v0.4.3
`proc-macro2` v1.0.23 -> v1.0.24
`rustc-demangle` v0.1.16 -> v0.1.17
`serde_json` v1.0.57 -> v1.0.58
`syn` v1.0.42 -> v1.0.43
`thiserror` v1.0.20 -> v1.0.21
`thiserror-impl` v1.0.20 -> v1.0.21
> Cargo.lock: update deps & subtle-encoding: clippy

- Cargo.lock
- stdtx/CHANGES.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- MSRV 1.44+ ([#515])
- Replace `signatory-secp256k1` with `k256` ([#514])
[#515]: https://github.com/iqlusioninc/crates/pull/515
[#514]: https://github.com/iqlusioninc/crates/pull/514
> stdtx v0.3.0

- .github/workflows/rust.yml
- Cargo.lock
- hkd32/Cargo.toml
- hkd32/src/key_material.rs
- hkd32/src/lib.rs
- hkd32/src/mnemonic/phrase.rs
The latter provides a `no_std`-friendly abstraction over the former
> Replace `getrandom` with `rand_core`

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- Replace `getrandom` with `rand_core` ([#540])
- Replace `lazy_static` with `once_cell` ([#539])
- Bump `hmac` to v0.10; pbkdf2 to v0.6 ([#538])
- MSRV 1.44+ ([#515])
[#540]: https://github.com/iqlusioninc/crates/pull/540
[#539]: https://github.com/iqlusioninc/crates/pull/539
[#538]: https://github.com/iqlusioninc/crates/pull/538
[#515]: https://github.com/iqlusioninc/crates/pull/515
> hkd32 v0.5.0

- Cargo.lock
- stdtx/Cargo.toml
- stdtx/src/address.rs
- stdtx/src/amino/builder.rs
- stdtx/src/amino/msg.rs
- stdtx/src/amino/msg/builder.rs
- stdtx/src/amino/schema.rs
- stdtx/src/amino/schema/definition.rs
- stdtx/src/amino/schema/value_type.rs
- stdtx/src/amino/type_name.rs
- stdtx/src/decimal.rs
- stdtx/src/error.rs
- stdtx/src/lib.rs
> stdtx: replace `anomaly` with `eyre`

- .github/workflows/rust.yml
- Cargo.lock
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- stdtx/src/proto.rs
- stdtx/src/proto/builder.rs
- stdtx/src/proto/msg.rs
Adds preliminary (untested) support for creating and signing transactions in the new Protocol Buffers-based transaction format (presently in `v1beta1` format).
Uses the `ibc-proto` crate for Protobuf definitions. Code largely adapted from `ibc-rs` (with credit).
> stdtx: initial Protocol Buffers support

- zeroize/src/lib.rs
I was looking at docs.rs and noticed that some of the code here could be deduped
> Simplify String::zeroize

- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize/src/x86.rs
Adds `Zeroize` impls for the following x86/x86_64 SIMD register types, gated on the corresponding `target_feature`s they depend upon:
- `__m128`
- `__m128d`
- `__m128i`
- `__m256`
- `__m256d`
- `__m256i`
> zeroize: add support for x86(_64) SIMD registers

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- `Zeroize` support for x86(_64) SIMD registers ([#577])
- Simplify `String::zeroize` ([#563])
- MSRV 1.44+ ([#515])
[#577]: https://github.com/iqlusioninc/crates/pull/577
[#563]: https://github.com/iqlusioninc/crates/pull/563
[#515]: https://github.com/iqlusioninc/crates/pull/515
> zeroize 1.2.0

- Cargo.lock
- stdtx/CHANGES.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- MSRV 1.46+ ([#588])
- Bump `ecdsa` dependency to v0.10 ([#588])
- Bump `k256` dependency to v0.7 ([#588])
- Replace `anomaly` with `eyre` ([#555])
[#588]: https://github.com/iqlusioninc/crates/pull/588
[#555]: https://github.com/iqlusioninc/crates/pull/555
> stdtx v0.4.0

- zeroize/src/lib.rs
This allows types like `Zeroizing<Box<[u8]>>` which would otherwise fail
with "the trait `DefaultIsZeroes` is not implemented for `Box<[u8]>`"
> Add impl Zeroize for Box<[Z]>

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- bip32/Cargo.toml
- bip32/LICENSE-APACHE
- bip32/LICENSE-MIT
- bip32/src/child_number.rs
- bip32/src/derivation_path.rs
- bip32/src/error.rs
- bip32/src/extended_secret_key.rs
- bip32/src/lib.rs
- bip32/src/secret_key.rs
- bip32/tests/bip39_vectors.rs
- bip32/tests/test_vectors.rs
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- hkd32/src/mnemonic.rs
- hkd32/src/mnemonic/bits.rs
- hkd32/src/mnemonic/language.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/src/mnemonic/seed.rs
Initial implementation with `secp256k1` derivation support
> `bip32` crate

- bip32/Cargo.toml
- bip32/src/error.rs
- bip32/src/secret_key.rs
Impls the `bip32::secret_key::SecretKey` trait for `k256::ecdsa::SigningKey`, allowing derivation of verification keys.
> bip32: support for deriving extended k256::ecdsa::SigningKey

- bip32/src/lib.rs
Gated on the `secp256k1` cargo feature
> bip32: re-export `k256` as `secp256k1`

- Cargo.lock
- zeroize/derive/CHANGES.md
- zeroize/derive/Cargo.toml
- Bump MSRV to 1.47+ ([#685])
[#685]: https://github.com/iqlusioninc/crates/pull/685
> zeroize_derive v1.1.0

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- impl `Zeroize` for `Box<[Z]>` ([#615])
- Clear residual space within `Option` ([#687])
- Ensure `Option` is `None` when zeroized ([#649])
- Bump MSRV to 1.47 ([#685])
[#615]: https://github.com/iqlusioninc/crates/pull/615
[#649]: https://github.com/iqlusioninc/crates/pull/649
[#685]: https://github.com/iqlusioninc/crates/pull/685
[#687]: https://github.com/iqlusioninc/crates/pull/687
> zeroize v1.3.0

- .github/workflows/iqhttp.yml
- iqhttp/Cargo.toml
- iqhttp/src/lib.rs
- iqhttp/src/serializers.rs
- mintscan/Cargo.toml
Unfortunately `hyper` doesn't provide `serde` serializers for `hyper::Uri` (even in the `hyper_serde` crate).
This adds a small helper annotation:
#[serde(with = "iqhttp::serializers::uri)]
This can be added to fields to serialize/deserialize `iqhttp::Uri` (a re-export of `hyper::Uri`) using serde.
> iqhttp: URI serialization helpers

- .github/workflows/bip32.yml
- Cargo.lock
- bip32/Cargo.toml
- bip32/src/extended_key.rs
- bip32/src/extended_secret_key.rs
- bip32/src/lib.rs
Extracts xpub/xprv parsing into an `ExtendedKey` type which handles Base58Check decoding and parsing of the encoded fields.
> bip32: add ExtendedKey type

- bip32/src/extended_secret_key.rs
- hkd32/src/lib.rs
- hkd32/src/mnemonic.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/src/mnemonic/seed.rs
Moves the `SEED_SIZE` constant to `Seed::SIZE`, and exposes a sized array (`[u8; 64]`) from the `as_bytes()` method.
Additionally adds an `AsRef` impl on `Seed`, and bounds the `bip32` crate's `ExtendedSecretKey` derivation on a seed-sized value.
Finally, it renames `BIP39_DOMAIN_SEPARATOR` as it's a non-secret value.
> hkd32: namespace Seed::SIZE; expose [u8; 64]

- bip32/src/child_number.rs
- bip32/src/error.rs
- bip32/src/extended_key.rs
- bip32/src/extended_private_key.rs
- bip32/src/lib.rs
- bip32/src/private_key.rs
- bip32/src/version.rs
- bip32/tests/bip39_vectors.rs
- hkd32/src/lib.rs
- hkd32/src/mnemonic/seed.rs
- Adds a `Version` enum for parsing the leading version bytes in an extended key (e.g. `xprv` vs `xpub`)
- Uses "private key" nomenclature so as to better match the BIP32 spec
- Adds `From` impls and methods providing more granular creation and/or conversion of `ChildNumber`s and `ExtendedPrivateKey`
- Adds `XPrv` alias for `ExtendedPrivateKey<k256::ecdsa::SigningKey>`
- Tests that the derived root `XPrv` for a given seed matches the `XPrv` parsed from a string in the test vectors
> bip32: extract Version enum, add impls, and additional tests

- bip32/src/child_number.rs
- bip32/src/extended_private_key.rs
- bip32/src/private_key.rs
- bip32/tests/bip39_vectors.rs
Changes existing references to "secret key" (as used in the RustCrypto crates, notably `k256`) to "private key" exclusively, so as to better match the BIP32 spec's nomenclature.
> bip32: standardize on "private key" nomenclature

- bip32/src/extended_private_key.rs
- bip32/src/private_key.rs
The BIP32 spec is somewhat ambiguous as to how modular reductions of keys are to be handled, and does not appear to stipulate any special handling of a key of all zeroes.
Based on the following remarks in the spec:
> Split I into two 32-byte sequences, IL and IR.
> The returned child key ki is parse256(IL) + kpar (mod n).
...it is assumed that all scalars are derived via a "narrow" modular reduction (i.e. 256-bit input), and that there is no special handling of the case of all zeroes.
This commit implements this approach in the `PrivateKey::from_bytes` method, reducing secp256k1 scalars.
For simplicity's sake, at least for now this same behavior is applied to parsed `xprv` keys, which are allowed to overflow the curve's order and are reduced by this API (as opposed to being rejected), but …
> bip32: reduce secp256k1 keys mod n

- bip32/src/extended_key.rs
- bip32/src/extended_private_key.rs
- bip32/src/prefix.rs
- bip32/tests/bip32_vectors.rs
Adds encoding support with the following impls:
- `write_base58`: a `no_std`-friendly method that accepts a buffer
- `Display`: standard Rust trait; provides `ToString` impl
> bip32: support for serializing `ExtendedKey` as Base58Check

- bip32/src/extended_private_key.rs
- hkd32/src/mnemonic.rs
- hkd32/src/mnemonic/seed.rs
The `hkd32` crate previously provided a minimal implementation of BIP32, but not one that's particularly useful.
The recommended replacement is to use the `bip32` crate (which otherwise only uses `hkd32` to implement BIP39)
> hkd32: remove `derive_subkey` and domain separator constant

- .github/workflows/bip32.yml
- Cargo.lock
- bip32/Cargo.toml
- bip32/src/child_number.rs
- bip32/src/extended_key.rs
- bip32/src/extended_private_key.rs
- bip32/src/extended_public_key.rs
- bip32/src/lib.rs
- bip32/src/private_key.rs
- bip32/src/public_key.rs
- bip32/tests/bip32_vectors.rs
- bip32/tests/bip39_vectors.rs
Adds a `PublicKey` trait and uses it as the bound for the associated `PrivateKey::PublicKey` type.
Adds `ExtendedPublicKey`, the extended key analogue of `ExtendedPrivateKey`, and support for serializing/deserializing them to/from `ExtendedKey`, as well as computing it from an `ExtendedPrivateKey`.
When the `secp256k1` feature is enabled, adds an `XPub` alias for an `ExtendedPublicKey` whose `K: PublicKey` is a `k256::ecdsa::VerifyingKey`.
Finally, augments the test vectors in `tests/bip32_vectors.rs` to include `xpub...` strings, and ensures keys are derived and serialized correctly.
> bip32: add PublicKey/ExtendedPublicKey and XPub alias

- bip32/src/extended_key.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/lib.rs
- hkd32/src/mnemonic/phrase.rs
Moves `ExtendedPrivateKey`/`ExtendedPublicKey` under the `extended_key` module, keeping it private and re-exporting them at the toplevel.
> bip32: refactor `extended_key` module

- bip32/src/extended_key.rs
- bip32/src/extended_key/attrs.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/lib.rs
- bip32/src/prefix.rs
Extracts a type for carrying around attributes/metadata related to extended keys, which includes:
- depth
- parent fingerprint
- child number
- chain code
> bip32: extract `ExtendedKeyAttrs` type

- bip32/Cargo.toml
- bip32/src/child_number.rs
- bip32/src/derivation_path.rs
- bip32/src/error.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/prefix.rs
- Adds `Display` impls to both
- Adds additional constructor methods for `ChildNumber`
- Adds `Extend` and `IntoIterator` impls for `DerivationPath`
> bip32: `ChildNumber` and `DerivationPath` improvements

- .github/workflows/bip32.yml
- .github/workflows/hkd32.yml
- Cargo.lock
- bip32/Cargo.toml
- bip32/src/derivation_path.rs
- bip32/src/extended_key.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/lib.rs
- bip32/tests/bip32_vectors.rs
- hkd32/Cargo.toml
- hkd32/tests/bip39_vectors.rs
The only thing that presently requires `alloc` is `DerivationPath`.
This commit makes `DerivationPath` optional, and feature-gated under a newly added `alloc` feature.
Additionally, this commit tests `no_std` builds of both `bip32` and `hkd32`, including builds on WASM.
> bip32: make "alloc" an optional feature (heapless support)

- Cargo.lock
- bip32/Cargo.toml
- bip32/README.md
- bip32/src/error.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/lib.rs
- bip32/src/prefix.rs
- bip32/src/private_key.rs
- bip32/src/public_key.rs
- bip32/tests/bip32_vectors.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/src/mnemonic/seed.rs
Adds support for deriving keys using the `secp256k1` crate, which wraps the Bitcoin Core libsecp256k1 C library.
Additionally, this commit fills out the remaining BIP32 test vectors, namely Test Vector 1 and Test Vector 4.
> bip32: secp256k1-ffi feature

- Cargo.lock
- bip32/Cargo.toml
- hkd32/Cargo.toml
This release is compatible with the current `tendermint` crate, and does not include #759.
We'll merge that after this prerelease.
> hkd32 v0.6.0-pre

- Cargo.lock
- bip32/Cargo.toml
- bip32/src/lib.rs
This is a tendermint-rs compatible prerelease which omits #759.
After merging that, we can cut a real initial release.
> bip32 v0.0.1

- Cargo.lock
- bip32/Cargo.toml
- bip32/src/private_key.rs
- bip32/src/public_key.rs
- hkd32/Cargo.toml
- stdtx/Cargo.toml
We were previously keeping these back to ensure compatibility with `tendermint-rs` for use with `bip32`, however one of the interesting features of `bip32` is that it's generic, which means we can still use it via simple newtype wrappers that provide the current implementation.
This commit bumps these dependencies so we can release with the latest versions.
> Bump `k256` to v0.9; `rand_core` to v0.6

- hkd32/CHANGELOG.md
- hkd32/src/lib.rs
- `Seed::new` method ([#729])
- `hmac` to v0.11 ([#704])
- `pbkdf2` to v0.8 ([#704])
- Rename `SEED_SIZE` to `Seed::SIZE` ([#728])
- MSRV 1.51 ([#755])
- Bump `rand_core` to v0.6 ([#759])
- `Seed::derive_subkey` ([#748])
- `BIP39_BASE_DERIVATION_KEY` constant ([#748])
[#704]: https://github.com/iqlusioninc/crates/pull/704
[#728]: https://github.com/iqlusioninc/crates/pull/728
[#729]: https://github.com/iqlusioninc/crates/pull/729
[#748]: https://github.com/iqlusioninc/crates/pull/748
[#755]: https://github.com/iqlusioninc/crates/pull/755
[#759]: https://github.com/iqlusioninc/crates/pull/759
> hkd32 v0.6.0

- Cargo.lock
- bip32/Cargo.toml
- bip32/README.md
- bip32/src/lib.rs
- bip32/tests/bip32_vectors.rs
- bip32/tests/bip39_vectors.rs
Fixes broken links, adds a limitations section to the rustdoc, and includes a full code example
> bip32: doc improvements and usage example

- Cargo.lock
- bip32/Cargo.toml
- bip32/src/private_key.rs
This release deprecates `verify_key` in favor of `verifying_key`
> bip32: bump `k256` crate dependency to v0.9.3

- .github/workflows/bip32.yml
- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/lib.rs
- bip32/src/private_key.rs
- bip32/src/public_key.rs
- bip32/tests/bip32_vectors.rs
Adds a `derive_child` method to the `PublicKey` trait which can be used for computing a child xpub from a parent xpub (i.e. non-hardened derivation support)
Additionally adds a corresponding `ExtendedPublicKey::derive_child` method which wraps up this derivation.
> bip32: add `(Extended)PublicKey::derive_child`

- bip32/src/extended_key/private_key.rs
- bip32/src/lib.rs
- bip32/src/private_key.rs
- bip32/src/public_key.rs
- bip32/tests/bip32_vectors.rs
The previous name was both long and somewhat confusing as `XPrv::new` also accepts a seed (and generates the root key).
The notable thing about `derive_from_path` is that it accepts a `DerivationPath` as an argument, so the name has been changed to both be shorter and reflect that it derives using a path.
> bip32: rename `XPrv::derive_child_from_seed` to `::derive_from_path`

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- Non-hardened derivation support with `XPub::derive_child` ([#772])
- Rename `XPrv::derive_child_from_seed` => `XPrv::derive_from_path` ([#773])
[#772]: https://github.com/iqlusioninc/crates/pull/772
[#773]: https://github.com/iqlusioninc/crates/pull/773
> bip32 v0.2.0

- bip32/src/lib.rs
Deriving child `XPub`s from a parent `XPub` was implemented in #772
> bip32: doc fixup

- Cargo.lock
- stdtx/CHANGELOG.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- MSRV 1.51+ ([#755])
- Bump `k256` to v0.9 ([#759])
- `rand_core` to v0.6 ([#759])
[#755]: https://github.com/iqlusioninc/crates/pull/755
[#759]: https://github.com/iqlusioninc/crates/pull/759
> stdtx v0.5.0

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- `From` conversions to `k256::ecdsa::*Key` ([#777])
[#777]: https://github.com/iqlusioninc/crates/pull/777
> bip32 v0.2.1

- signatory/src/key/store/fs.rs
Adds a function for creating a keystore if it doesn't exist, or opening an existing one if it does.
Underneath it eagerly attempts to open the keystore, and then handles errors by trying to create it (then open it again).
> signatory: add `FsKeyStore::create_or_open`

- signatory/Cargo.toml
- signatory/src/ecdsa.rs
- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/error.rs
- signatory/src/key/ring.rs
- signatory/src/lib.rs
Uses `doc_cfg` on https://docs.rs to annotate which crate features are required to use specific parts of the library.
> signatory: docs.rs config

- signatory/src/key/store/fs.rs
Support for importing PKCS#8 keys into `KeyRing`s.
> signatory: add `FsKeyStore::import`

- zeroize/src/lib.rs
IIUC after https://github.com/iqlusioninc/crates/pull/755 the MSRV of Zeroize is 1.51, which is the version that rust stabilized  the "minimum const generics" feature (https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1510-2021-03-25).
So I think there's no more reason to use a macro and restrict ourselves to arrays with length up to 64.
> Use const generics to implement Zeroize for Arrays

- .github/workflows/signatory.yml
- Cargo.lock
- signatory/Cargo.toml
- signatory/src/ecdsa.rs
- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/nistp256.rs
- signatory/src/key/handle.rs
Adds a `nistp256` crate feature which provides feature-gated support for ECDSA signatures using NIST's P-256 elliptic curve.
> signatory: ECDSA/P-256 support

- zeroize/src/lib.rs
Commits from #736, rebased on current `main`
> Zeroizing::clone_from now zeroizes the destination before cloning

- Cargo.lock
- zeroize/CHANGELOG.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
*NOTE: This release includes an MSRV bump to Rust 1.51. Please use `zeroize = "1.3.0"` if you would like to support older Rust versions.*
- Use const generics to impl `Zeroize` for `[Z; N]`; MSRV 1.51 ([#794])
- `Zeroizing::clone_from` now zeroizes the destination before cloning ([#801])
[#794]: https://github.com/iqlusioninc/crates/pull/794
[#801]: https://github.com/iqlusioninc/crates/pull/801
> zeroize v1.4.0

- Cargo.lock
- secrecy/CHANGELOG.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
*NOTE: This release includes an MSRV bump to Rust 1.51. Please use `secrecy = "0.7.0"` if you would like to support older Rust versions.*
- impl `From<T>` for `Secret` ([#482])
- Bump `bytes` to v1.0 ([#592])
- Switch to `resolver = "2"`; MSRV 1.51 ([#755])
[#482]: https://github.com/iqlusioninc/crates/pull/482
[#592]: https://github.com/iqlusioninc/crates/pull/592
[#755]: https://github.com/iqlusioninc/crates/pull/755
> secrecy v0.8.0

- zeroize/src/lib.rs
Implementing Zeroize for `[MaybeUninit<Z>]` is very helpful IMHO, because it allows to zeroize any custom heap allocated objects by just constructing a slice of `MaybeUninit`(as some of the buffer might not be initialized) and calling `zeroize()` on it.
I also changed the Vec implementation to zero out the full capacity and not just the uninitialized part, because I don't see any difference between the initialized and the unintialized, if the data in the buffer is secret then we should make sure we zero out all of the buffer.
The downside is that if the Vec contains a primitive(say `Vec<u8>`) then we'll zero the used space twice, so I can see arguments against it (currently the only time I can think this will matter is in Vecs with another indirection, like `Vec<Box<Z>>` or `Vec<&Z>`, and …
> Implement Zeroize for `[MaybeUninit<Z>]`

- Cargo.lock
- iqhttp/Cargo.toml
hardcoding `hyper` to v0.14.10 to see if that fixes version glob in [ deps.rs badge]( https://github.com/iqlusioninc/crates/pull/808).
> Cargo.lock: update deps

- datadog/Cargo.toml
hardcoding `hyper` to v0.14.10 in `datadog` crate to fix version glob in [deps.rs badge](https://github.com/iqlusioninc/crates/pull/808).
> Cargo.lock: update `hyper` dep

- .github/workflows/signatory.yml
- Cargo.lock
- signatory/Cargo.toml
- signatory/src/ecdsa.rs
- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/nistp256.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/ed25519.rs
- signatory/src/ed25519/keyring.rs
- signatory/src/ed25519/sign.rs
- signatory/src/ed25519/verify.rs
- signatory/src/error.rs
- signatory/src/key/handle.rs
- signatory/src/key/ring.rs
- signatory/src/lib.rs
Adds support for Ed25519 signing, verification, and keyrings, using `ed25519-dalek` as the backing implementation.
> signatory: Ed25519 support

- signatory/src/algorithm.rs
- signatory/src/ecdsa/keyring.rs
- signatory/src/key/ring.rs
The `Algorithm` enum was previously missing `EcdsaNistP256` and `Ed25519` variants, as it wasn't integral to how the keyring worked.
This commit adds those variants, and also uses `Algorithm` as the one way to parse PKCS#8 AlgorithmIdentifiers, ensuring that in the future additional algorithms will always need to be added to it.
> signatory: `Algorithm` enum improvements

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- signatory/src/lib.rs
- `ed25519::VerifyingKey::to_bytes` ([#834])
[#834]: https://github.com/iqlusioninc/crates/pull/834
> signatory v0.23.2

- bip32/src/public_key.rs
As explained in #858, using GenericArray::as_slice is more deterministic for the compiler when it is working against conflicting versions of generic-array; at least, that is the theory behind why `as_ref` without any type annotations is causing complier confusion, given the wider set of `AsRef` impls on `GenericArray` in 0.14 vs. 0.12.
I think regardless of my personal build issue, this update to `as_slice` is safe and could be argued as a better fit.
> Resolve a build issue with bip32 when there are competing versions of generic-array in the dependency tree.

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- Avoid `AsRef` ambiguity with `generic-array` ([#859])
[#859]: https://github.com/iqlusioninc/crates/pull/859
> bip32 v0.2.2

- zeroize/src/lib.rs
Uses rustdoc's linking convention to link to types/functions
> zeroize: modernize docs

- zeroize/src/lib.rs
Simplifies initialization of a `Zeroizing` type to its default value.
Closes #849.
> zeroize: derive `Default` on `Zeroizing`

- zeroize/derive/CHANGELOG.md
- Backport #847 but with a 1.47+ MSRV
Closes #880
> zeroize_derive v1.1.1

- Cargo.lock
- mintscan/CHANGELOG.md
- mintscan/Cargo.toml
- mintscan/src/lib.rs
- Bump `tendermint` crate from 0.22.0 to 0.23.0 ([#897])
[#897]: https://github.com/iqlusioninc/crates/pull/897
> mintscan v0.3.0

- anomaly/README.md
- zeroize/README.md
- `anomaly` has been deprecated
- `zeroize` has been moved
This removes some short-lived notices about these two crates
> Remove `anomaly` and `zeroize`

- bip32/src/extended_key.rs
- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/mnemonic/phrase.rs
- bip32/src/prefix.rs
- bip32/src/public_key.rs
- hkd32/src/key_material.rs
- hkd32/src/mnemonic/phrase.rs
- hkd32/tests/bip39_vectors.rs
- mintscan/src/deserializers.rs
- mintscan/tests/integration.rs
- signatory/src/algorithm.rs
- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/nistp256.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/ed25519/sign.rs
- signatory/src/ed25519/verify.rs
- signatory/src/key/ring.rs
- signatory/src/key/store/fs.rs
- stdtx/src/address.rs
- stdtx/src/amino/msg/builder.rs
- stdtx/src/amino/type_name.rs
- stdtx/src/decimal.rs
All of our crates are 2021 edition, which added these traits to the prelude so they no longer need to be imported.
> Remove `TryFrom`/`TryInto` imports

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- Decouple from `hkd32` ([#907])
- Bump `k256` dependency to v0.10 ([#938])
- Bump `secp256k1` (FFI) dependency to v0.21 ([#942])
[#907]: https://github.com/iqlusioninc/crates/pull/907
[#938]: https://github.com/iqlusioninc/crates/pull/938
[#942]: https://github.com/iqlusioninc/crates/pull/942
> bip32 v0.3.0

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- signatory/src/lib.rs
- Bump `k256` dependency to v0.10 ([#938])
[#938]: https://github.com/iqlusioninc/crates/pull/938
> signatory v0.24.0

- Cargo.lock
- stdtx/CHANGELOG.md
- stdtx/Cargo.toml
- stdtx/src/lib.rs
- Bump `k256` dependency to v0.10 ([#938])
[#938]: https://github.com/iqlusioninc/crates/pull/938
> stdtx v0.6.0

- iqhttp/src/https_client.rs
- iqhttp/src/lib.rs
Adds support for configuring HTTP headers to send as part of the request.
Uses `hyper::HeaderMap` as the internal data structure for headers, making them yet another thin wrapper around `hyper`.
This functionality existed somewhat before, but as a crate-internal feature only. This commit exposes it as a first-class feature.
> iqhttp: add `HttpsClient::{add_header, headers_mut}`

- Cargo.lock
- iqhttp/CHANGELOG.md
- iqhttp/Cargo.toml
- iqhttp/README.md
- iqhttp/src/lib.rs
- mintscan/Cargo.toml
- `HttpsClient::{add_header, headers_mut}` methods ([#981])
[#981]: https://github.com/iqlusioninc/crates/pull/981
> iqhttp v0.2.0

- Cargo.lock
- iqhttp/LICENSE-MIT
- mintscan/CHANGELOG.md
- mintscan/Cargo.toml
- mintscan/LICENSE-MIT
- mintscan/README.md
- mintscan/src/lib.rs
- `Referer` header ([#982])
- Bump `iqhttp` dependency to v0.2.0 ([#984]) 
[#982]: https://github.com/iqlusioninc/crates/pull/982
[#984]: https://github.com/iqlusioninc/crates/pull/984
> mintscan v0.4.0

- bip32/src/prefix.rs
Now that we're MSRV 1.57, const panic can be used because it was stabilized in that release.
> bip32: use const panic for `Prefix::from_parts_unchecked`

- bip32/src/lib.rs
The example code at `lib.rs` is repeating the assertion of `child_xprv_str`, while the `child_xpub_str` remains unused/untested.
> Fix wrong example in `lib.rs`

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/LICENSE-MIT
- bip32/README.md
- bip32/src/lib.rs
- Bump `pbkdf2` to 0.11.0 ([#983])
- Bump `hmac` to v0.12 ([#994])
- Bump `k256` to v0.11 ([#994])
- Bump `p256` to v0.11 ([#994])
- Bump `pbkdf2` to v0.10 ([#994])
- Bump `sha2` to v0.10 ([#994])
- Replace `ripemd160` dependency with `ripemd` ([#994])
- MSRV 1.57 ([#994], [#995])
- Use const panic for `Prefix::from_parts_unchecked` ([#995])
[#983]: https://github.com/iqlusioninc/crates/pull/983
[#994]: https://github.com/iqlusioninc/crates/pull/994
[#995]: https://github.com/iqlusioninc/crates/pull/995
> bip32 v0.4.0

- Cargo.lock
- bip32/CHANGELOG.md
- hkd32/CHANGELOG.md
- hkd32/Cargo.toml
- Impl for `std::error::Error` ([#932])
- Bump `pbkdf2` to 0.11.0 ([#983])
- Bump `hmac` to v0.12 ([#994])
- Bump `sha2` to v0.10 ([#994])
[#932]: https://github.com/iqlusioninc/crates/pull/932
[#983]: https://github.com/iqlusioninc/crates/pull/983
[#994]: https://github.com/iqlusioninc/crates/pull/994
> hkd32 v0.7.0

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- signatory/src/lib.rs
- Bump `ecdsa` to v0.14 ([#994])
- Bump `k256` to v0.11 ([#994])
- Bump `p256` to v0.11 ([#994])
- Bump `pkcs8` to v0.9 ([#994])
- Bump `sha2` to v0.10 ([#994])
- MSRV 1.57 ([#994])
[#994]: https://github.com/iqlusioninc/crates/pull/994
> signatory v0.25.0

- Cargo.lock
- stdtx/CHANGELOG.md
- stdtx/Cargo.toml
- Bump `k256` to v0.11; `sha2` to v0.10 ([#994])
[#994]: https://github.com/iqlusioninc/crates/pull/994
> stdtx v0.7.0

- signatory/src/ecdsa/nistp256.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/ed25519/sign.rs
This allows the keyring types to be shared across threads
> signatory: add `Send + Sync` bounds to signer `Box`es

- Cargo.lock
- signatory/Cargo.toml
- signatory/src/algorithm.rs
- signatory/src/ecdsa.rs
- signatory/src/ecdsa/nistp384.rs
- signatory/src/key/handle.rs
Adds a `nistp384` crate feature which provides feature-gated support for ECDSA signatures using NIST's P-384 elliptic curve.
> signatory: ECDSA/P-384 support

- signatory/CHANGELOG.md
- signatory/Cargo.toml
- `Send + Sync` bounds to inner `Box` for signer types ([#1037])
- ECDSA/P-384 support ([#1039])
[#1037]: https://github.com/iqlusioninc/crates/pull/1037
[#1039]: https://github.com/iqlusioninc/crates/pull/1039
> signatory v0.26.0

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- Support for private `ExtendedKey` conversion to `ExtendedPublicKey` ([#1021])
- Upgrade elliptic curve crates; MSRV 1.65 ([#1105])
- `ecdsa` v0.16
- `ed25519-dalek` v2.0.0-pre.0
- `k256` v0.13
- `p256` v0.13
- `p384` v0.13
- Bump `secp256k1` crate dependency to v0.27 ([#1115])
[#1021]: https://github.com/iqlusioninc/crates/pull/1021
[#1105]: https://github.com/iqlusioninc/crates/pull/1105
[#1115]: https://github.com/iqlusioninc/crates/pull/1115
> bip32 v0.5.0

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- Bump `ecdsa`to v0.16 ([#1105])
- Bump `k256` to v0.13 ([#1105])
- Bump `p256` to v0.13 ([#1105])
- Bump `p384` to v0.13 ([#1105])
- Bump `ed25519-dalek` to 2.0.0-rc.2 ([#1113])
[#1105]: https://github.com/iqlusioninc/crates/pull/1105
[#1113]: https://github.com/iqlusioninc/crates/pull/1113
> signatory v0.27.0

- bip32/src/extended_key/public_key.rs
This adds a new function to construct a `ExtendedPublicKey` the only way to construct it from a public key right now is via `TryFrom<ExtendedKey>` or `FromStr` both require extra unnecessary computation and unwraps
> bip32: Add ExtendedPublicKey::new

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- `ExtendedPublicKey::new` ([#1136])
- Bump `bs58` to v0.5 ([#1139])
[#1136]: https://github.com/iqlusioninc/crates/pull/1136
[#1139]: https://github.com/iqlusioninc/crates/pull/1139
> bip32 v0.5.1

- bip32/src/extended_key/private_key.rs
- bip32/src/extended_key/public_key.rs
- bip32/src/private_key.rs
- bip32/src/public_key.rs
Closes #1185
Adds `PublicKey::derive_tweak()` and `PrivateKey::derive_tweak()` exposing the tweak-generation API that extended keys use. These methods have default implementations, so it's not a breaking change. This is the minimum that I need to use BIP-32 with DKG shares.
Alternatively, these can be separate functions, to illustrate that the implementation is standardized and should not be overridden. 
Possible further work:
- Add methods to generate a tweak chain for the given derivation path and apply it to a `PrivateKey` or `PublicKey`. I currently do it manually in my own code.
- Wrap the tweak in its own `ZeroizeOnDrop`-able type instead of using plain `PrivateKeyBytes`. This will be a breaking change.
- Implement the logic generically using `ecdsa` and `elliptic-curve` traits. …
> bip32: add `PrivateKey::derive_tweak()` and `PublicKey::derive_tweak()`

- Cargo.lock
- hkd32/Cargo.toml
- hkd32/src/key_material.rs
- hkd32/src/pathbuf.rs
It's being used for trivial impls of the `zeroize` traits, and in the meantime `syn` MSRV changes are breaking the crate's current MSRV.
The derived usages are trivially rewritten without the whole proc macro stack, and really these types shouldn't have `Zeroize` impls at all, but instead impl `Drop` and `ZeroizeOnDrop`.
> hkd32: remove usage of `zeroize_derive`

- .github/workflows/canonical-path.yml
- .github/workflows/iqhttp.yml
- Cargo.lock
- canonical-path/Cargo.toml
- canonical-path/README.md
- iqhttp/Cargo.toml
- iqhttp/README.md
Updates the following dependencies:
$ cargo update
Updating crates.io index
Locking 117 packages to latest compatible versions
Adding addr2line v0.22.0 (latest: v0.24.0)
Adding adler v1.0.2
Updating autocfg v1.1.0 -> v1.3.0
Adding backtrace v0.3.73
Adding base64 v0.21.7 (latest: v0.22.1)
Updating bitflags v1.3.2 -> v2.6.0
Updating bs58 v0.5.0 -> v0.5.1
Updating bumpalo v3.12.0 -> v3.16.0
Updating bytes v1.4.0 -> v1.6.1
Updating cc v1.0.79 -> v1.1.5
Updating const-oid v0.9.2 -> v0.9.6
Updating core-foundation v0.9.3 -> v0.9.4
Updating core-foundation-sys v0.8.3 -> v0.8.6
Updating cpufeatures v0.2.6 -> v0.2.12
Updating crypto-bigint v0.5.1 -> v0.5.5
Updating curve25519-dalek v4.0.0 -> v4.1.3
Updating curve25519-dalek-derive v0.1.0 -> v0.1.1
Updating der v0.7.2 -> v0.7.9
Updating ecdsa …
> Cargo.lock: bump dependencies

- secrecy/Cargo.toml
> secrecy: disable `serde` default features

- secrecy/src/lib.rs
Previously they were named `*new_with_ctr` which is a somewhat confusing name (particularly to anyone who works in cryptography where "ctr" registers as counter mode).
The `init_with` name is commonly used for these sorts of `Fn`-based constructors.
> secrecy: rename constructor methods to `init_with`

- secrecy/src/lib.rs
Adds a type alias for `SecretBox<str>` to replace the previous `SecretString` type and provide a better migration path.
To support this, we need to add `?Sized` bounds to `SecretBox` so `SecretBox<str>` is valid.
> secrecy: add `SecretString` replacement; ?Sized bounds

- secrecy/src/lib.rs
Adds a type alias for `SecretBox<[S]>` as a more convenient way to work with boxed secret slices.
> secrecy: add `SecretSlice<S>`

- Cargo.lock
- secrecy/CHANGELOG.md
- secrecy/Cargo.toml
- secrecy/LICENSE-MIT
- secrecy/README.md
This release represents a significant redesign of the `secrecy` crate.
The most notable change is the generic `Secret<T>` type has been removed: instead use `SecretBox<T>`
which stores secrets on the heap instead of the stack. Many of the other changes fall out of this
change and things which were previously type aliases of `Secret<T>` are now type aliases of
`SecretBox<T>`.
This unfortunately means this crate no longer has support for "heapless" `no_std` targets. We don't
have a good solution for these targets, which was a motivation for this change in the first place.
- `SecretBox::{init_with, try_init_with}` ([#1212])
- `SecretBox::init_with_mut` ([#1213])
- `?Sized` bounds for `SecretBox` ([#1213])
- `SecretSlice<T>` ([#1214])
- MSRV 1.60 ([#1105]) …
> secrecy v0.10.0

- secrecy/src/lib.rs
Fixes a regression from previous releases.
Closes #1216
> secrecy: impl `Clone` for `SecretString`

- Cargo.lock
- secrecy/CHANGELOG.md
- secrecy/Cargo.toml
- Impl `Clone` for `SecretString` ([#1217])
[#1217]: https://github.com/iqlusioninc/crates/pull/1217
> secrecy v0.10.1

- secrecy/Cargo.toml
- secrecy/src/lib.rs
It needs a special impl since `SecretBox<str>` (which `SecretString` is a type alias for) doesn't meet the `Clone` bound (i.e. `str` doesn't impl `Clone`).
Closes #1219
> secrecy: impl `Deserialize` for `SecretString`

- secrecy/src/lib.rs
Impls `Clone` for `SecretSlice` when the `S` generic type is `CloneableSecret + Zeroize`.
As originally requested in #1070, also marks the integer primitive types as `CloneableSecret`, which makes it possible to clone a `SecretSlice<u8>`.
Closes #1233
> secrecy: make integer primitive `SecretSlice`s cloneable

- secrecy/src/lib.rs
fixes https://github.com/iqlusioninc/crates/issues/1234
> secrecy: Add FromStr impl for SecretString

- secrecy/src/lib.rs
Adds a `CloneableSecret` for arrays of types which are themselves `CloneableSecret`
> secrecy: impl `CloneableSecret` for arrays

- .github/workflows/workspace.yml
- .typos.toml
Automatically check repo for typos, which should hopefully cut down on typo correction PRs:
https://github.com/crate-ci/typos
> CI: add `typos` action

- signatory/src/key/name.rs
> chore: add missing backticks
