iqlusioninc/crates

- .circleci/config.yml
- tai64/Cargo.toml
- tai64/README.md
- tai64/src/lib.rs
Adds a "chrono" feature with support for converting to/from chrono's `DateTime<Utc>` type
> tai64: chrono support

- .circleci/config.yml
- Dockerfile
> Dockerfile: add llvm-toolset-7

- Cargo.lock
- Cargo.toml
- README.md
- iq-cli/Cargo.toml
- iq-cli/README.md
- iq-cli/src/lib.rs
- iq-cli/src/shell.rs
Cargo-like colored command line interfaces
> iq-cli: Initial crate

- Cargo.lock
- Cargo.toml
- README.md
- cargo-rpm/Cargo.toml
- keyuri/Cargo.toml
- keyuri/README.md
- keyuri/src/bech32k/base32.rs
- keyuri/src/bech32k/checksum.rs
- keyuri/src/bech32k/error.rs
- keyuri/src/bech32k/mod.rs
- keyuri/src/lib.rs
keyuri is a crate for representing cryptographic keys and fingerprints using the URI generic syntax.
bech32k is a slightly tweaked version of bech32, and leverages the separators that already exist in the URI generic syntax (namely ';')
> keyuri: Initial crate with bech32k support

- cargo-rpm/README.md
This project can now be found at:
https://github.com/RustRPM/cargo-rpm
> cargo-rpm: Delete directory

- appveyor.yml
- iq-cli/Cargo.toml
- iq-cli/README.md
- iq-cli/src/shell/isatty.rs
Tests the `iq-cli` crate on Windows:
- 64-bit Windows only
- Visual Studio 2017 target
> appveyor.yml: Initial configuration

- iq-cli/src/macros/status.rs
Adds back `status_warn!` and `status!`, and implements all other status macros in terms of `status!` and `status_nojust!`
> iq-cli: Add back all of the original status macros

- abscissa/README.md
- abscissa_derive/README.md
Use SVG logos from https://www.iqlusion.io
> abscissa/README.md: Use SVG logo

- .circleci/config.yml
- Dockerfile
We now no longer need nightly at all, as clippy builds on stable
> Dockerfile: Update to Rust 1.29

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
* #83: Documentation improvements.
> zeroize v0.1.1

- zeroize/README.md
They're rendering wrong on GitHub and crates.io
> zeroize/README.md: Fix intrinsic links

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- #86: README.md: Fix intrinsic links.
> zeroize v0.1.2

- subtle-encoding/src/base64.rs
- subtle-encoding/src/hex.rs
Tests both encoders for all lengths between 0 and 64 bytes.
> subtle-encoding: Add more hex and base64 tests

- Cargo.lock
- canonical-path/CHANGES.md
- canonical-path/Cargo.toml
- canonical-path/src/lib.rs
> canonical-path v1.0.0

- Cargo.lock
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/src/lib.rs
> tai64 v1.0.0

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
> zeroize v0.2.0

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- #104 Replace `secure_zero_memory` with `Zeroize`.
> zeroize v0.3.0

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- #106 Bump zeroize dependency to 0.3
> subtle-encoding v0.2.2

- Cargo.lock
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- #108 Impl `Zeroize` trait on concrete types.
> zeroize v0.4.0

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- #109 Bump zeroize dependency to 0.4
> subtle-encoding v0.2.3

- .travis.yml
- Cargo.lock
- gaunt/Cargo.toml
- gaunt/src/connection.rs
- gaunt/src/lib.rs
- zeroize/src/stable/mod.rs
Optionally, and disabled by default.
> gaunt: Use slog for logging

- zeroize/src/lib.rs
Uses the `fence` and `compile_fence` functions to ensure LLVM reordering is fenced using the strictest ordering available (`Ordering::SeqCst`).
Additionally this adds a `ZeroizeWithDefault` trait which implements `Zeroize` using a volatile set of a type's default. This trait is then used as the bounds for the `IterMut` and `slice` implementations, which permits slightly more efficient implementations.
Finally, special cases are added for zeroing byte slices and arrays on nightly using the `volatile_set_memory` intrinsic, which should provide the best performance for these cases.
> zeroize: Use core::sync::atomic fences

- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Update to zeroize 0.5 (#149)
> subtle-encoding v0.3.1

- zeroize/src/lib.rs
This renames the marker trait for values which can be zeroed out with their Default value to one which delares a property of the type, rather than a zeroize implementation detail.
> zeroize: Rename ZeroizeWithDefault to DefaultIsZeroes (closes #162)

- Cargo.lock
- zeroize/Cargo.toml
- zeroize_derive/CHANGES.md
- zeroize_derive/Cargo.toml
- zeroize_derive/README.md
- zeroize_derive/src/lib.rs
> zeroize_derive v0.1.0

- zeroize/src/lib.rs
When zeroing either [Z] or [Z; N], where `Z: DefaultIsZeroes`, i.e. a contiguous memory region we want to fill with `Z::default()` we can (at such a time it becomes available) take advantage of using
an atomic memset-like implementation which can be implemented efficiently.
This change adds explicit bounds for arrays of up to size 64, and relaxes the `IterMut` bounds from `DefaultIsZeroes` to `Zeroize`, allowing it to be the fallback "slow mode" for dealing with cases where a fast path isn't available.
TODO: Const generics
> zeroize: Add explicit array impls for DefaultIsZeroes

- Cargo.lock
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize/tests/zeroize_derive.rs
- zeroize_derive/CHANGES.md
- zeroize_derive/Cargo.toml
- zeroize_derive/README.md
- Use synstructure for custom derive (#185)
- Add explicit array impls for `DefaultIsZeroes` (#184)
- Remove `nightly` feature (#183)
- Add `Zeroizing<Z>` to zeroize values on drop (#182)
> zeroize v0.7.0

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/error.rs
- subtle-encoding/src/lib.rs
- subtle-encoding/src/prelude.rs
> subtle-encoding v0.3.5

- Cargo.lock
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize_derive/Cargo.toml
- Impl `Drop` by default when deriving `Zeroize` (#188)
> zeroize v0.8.0

- Cargo.lock
- canonical-path/CHANGES.md
- canonical-path/Cargo.toml
- Canonicalize `current_exe()` (#198)
> canonical-path v2.0.1

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- canonical-path/README.md
- secrecy/Cargo.toml
- secrecy/LICENSE-MIT
- secrecy/README.md
- secrecy/src/lib.rs
- subtle-encoding/README.md
- zeroize/README.md
This is largely an extraction of the `secrets.rs` type from Abscissa:
https://github.com/iqlusioninc/abscissa/blob/9bd38d43f605d9c04c2b11fec34fbf6d947ed7b7/src/secrets.rs
This commit extracts it into a separate crate so it can be used by non-Abscissa users.
> secrecy: Initial crate

- Cargo.lock
- secrecy/Cargo.toml
- secrecy/src/lib.rs
> secrecy v0.1.0

- canonical-path/README.md
- gaunt/README.md
- secrecy/README.md
- subtle-encoding/README.md
Adds a little badge to note which crates forbid unsafe code.
> Add [unsafe|forbidden] badges to all crates which do so

- gaunt/README.md
- secrecy/README.md
- subtle-encoding/README.md
- tai64/README.md
- tai64/src/lib.rs
An idea worth considering.
https://internals.rust-lang.org/t/disabling-unsafe-by-default/7988
> Disabling ‘unsafe’ by default

- Cargo.lock
- README.md
- canonical-path/CHANGES.md
- canonical-path/Cargo.toml
- canonical-path/src/lib.rs
- Test all crates on Rust 1.35.0 (#206)
> canonical-path v2.0.2

- Cargo.lock
- README.md
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/src/lib.rs
- Test all crates on Rust 1.35.0 (#206)
> tai64 v2.0.1

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Add `CloneableSecret` marker trait (#210)
> secrecy v0.2.0

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Impl `Zeroize` for `Option<Z: Zeroize>` (#219)
> zeroize v0.9.1

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- `README.md`: add Gitter badges; update image links (#221)
> secrecy v0.2.2

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/src/lib.rs
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- `README.md`: add Gitter badges; update image links (#221)
> zeroize v0.9.2

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
> hkdf32 v0.1.1

- gaunt/README.md
- secrecy/README.md
- subtle-encoding/README.md
- tai64/README.md
Rust Safety Dance is a project to remove use of `unsafe` code in crates
in which the usage is unnecessary.
https://github.com/rust-secure-code/safety-dance/
> README.mds: Point (unsafe|forbiden) badges at Safety Dance

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
> hkd32 v0.1.2

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
- Improved attribute parser; fixes nightly build (#238)
> zeroize v0.9.3

- Cargo.lock
- gaunt/src/response/reader.rs
- Bump dependencies in `Cargo.lock`
- Add `dyn` where necessary
> Fix builds on nightly

- secrecy/src/lib.rs
Opt-in support for allowing `serde` to directly serialize secrets.
This is off-by-default as it provides a non-explicit means of exfiltrating secret values, however it has been frequently requested and in some cases could be useful (e.g. config files containing only secret values, like a keyring)
> secrecy: Add `SerializableSecret`

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- (Optionally) Impl `Zeroize` for `Bytes` and `BytesMut` (#258, #259)
> zeroize v0.10.1

- secrecy/Cargo.toml
> secrecy: Enable `all-features=true` for docs.rs

- Cargo.lock
- hkd32/Cargo.toml
- secrecy/Cargo.toml
- subtle-encoding/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- zeroize_derive/Cargo.toml
- Loosen `Vec` trait bounds for `Zeroize` (#267)
> zeroize v1.0.0-pre

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Upgrade to `zeroize` v1.0.0-pre (#268)
> subtle-encoding v0.4.1

- Cargo.lock
- harp/CHANGES.md
- harp/Cargo.toml
- harp/README.md
- harp/src/lib.rs
Renamed from gaunt:
https://crates.io/crates/gaunt
> harp v0.1.0

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/README.md
- secrecy/src/lib.rs
- Upgrade to `zeroize` v1.0.0-pre (#268)
> secrecy v0.4.1

- zeroize_derive/src/lib.rs
Removes support for the legacy `no_drop` attribute, which would previously print a deprecation warning. Now it is considered unrecognized and a hard error.
> zeroize_derive: Remove legacy `no_drop` attribute support

- Cargo.lock
- hkd32/Cargo.toml
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/src/lib.rs
- Upgrade to `zeroize` v1.0.0 (#279)
> subtle-encoding v0.5.0

- Cargo.lock
- hkd32/CHANGES.md
- hkd32/Cargo.toml
- hkd32/src/lib.rs
- Upgrade to `subtle-encoding` v0.5.0 (#283)
> hkd32 v0.3.1

- tai64/src/lib.rs
Provides the same functionality as the `from_slice()` method, but using the now standard `TryFrom` trait.
> tai64: Add TryFrom impls for slices

- Cargo.lock
- tai64/CHANGES.md
- tai64/Cargo.toml
- tai64/src/lib.rs
- Add `TryFrom` impls for slices (#288)
- Add (optional) `serde` support (#287)
> tai64 v3.1.0

- secrecy/src/lib.rs
Based on the discussion from https://github.com/interledger-rs/interledger-rs/issues/397#issuecomment-559610979
> Make secret exposure string more descriptive

- Cargo.lock
- secrecy/Cargo.toml
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Add `TryZeroize` trait (#307)
- Add `From<Z: Zeroize>` impl for `Zeroizing<Z>` (#304)
- Remove `bytes-preview` feature (#301)
> zeroize v1.1.0

- AUTHORS.md
- CONTRIBUTING.md
- secrecy/src/lib.rs
This PR adds `DebugSecret` impls for arrays.
> secrecy: Add DebugSecret impls for arrays

- Cargo.lock
- secrecy/CHANGES.md
- secrecy/Cargo.toml
- secrecy/src/lib.rs
- Impl `CloneableSecret` for `Secret<[T; N]>` where `T: Clone` (#311)
- Impl `DebugSecret` for `[T; N]` where `N` <= 64 (#310)
- Impl `FromStr` for `SecretString` (#309)
- Upgrade to `bytes` v0.5 (#301, #308, #312)
> secrecy v0.6.0

- Cargo.lock
- anomaly/CHANGES.md
- anomaly/Cargo.toml
- anomaly/src/lib.rs
> anomaly v0.1.2

- Cargo.lock
- Cargo.toml
- README.md
- stdtx/README.md
- vint64/Cargo.toml
- vint64/README.md
- vint64/benches/vint64.rs
- vint64/src/lib.rs
Simple and efficient variable-length integer encoding
> vint64: Initial crate implementation

- README.md
- anomaly/README.md
- canonical-path/README.md
- harp/README.md
- hkd32/README.md
- secrecy/README.md
- subtle-encoding/README.md
- tai64/README.md
- vint64/README.md
- vint64/src/lib.rs
- zeroize/README.md
- zeroize_derive/README.md
...and some other additional links
> README.md(s): fix GitHub actions links

- Cargo.lock
- vint64/CHANGES.md
- vint64/Cargo.toml
- vint64/src/lib.rs
> vint64 v0.1.1

- vint64/CHANGES.md
- vint64/Cargo.toml
- vint64/src/lib.rs
> vint64 v0.1.2

- Cargo.lock
- anomaly/Cargo.toml
- anomaly/README.md
- anomaly/src/context.rs
- anomaly/src/lib.rs
- anomaly/src/macros.rs
- anomaly/src/serializer.rs
Support for structured logging of errors using `serde` serializers
> anomaly: serde support

- Cargo.lock
- anomaly/CHANGES.md
- anomaly/Cargo.toml
- anomaly/src/lib.rs
- stdtx/Cargo.toml
- `serde` support (#353)
- Add generic `Error` type (#351)
> anomaly v0.2.0

- Cargo.lock
- subtle-encoding/CHANGES.md
- subtle-encoding/Cargo.toml
- subtle-encoding/README.md
- subtle-encoding/src/lib.rs
- Remove Bech32 max length restriction (#357)
> subtle-encoding v0.5.1

- Cargo.lock
- tai64/Cargo.toml
- tai64/src/lib.rs
Solve bugs by implementing zeroize manually
>  zeroize support 

- stdtx/src/address.rs
Allows addresses to be configured in config files
> stdtx: impl serde::Deserialize for Address

- stdtx/src/address.rs
- stdtx/src/amino_types.rs
- stdtx/src/error.rs
- stdtx/src/msg.rs
- stdtx/src/msg/value.rs
Support for parsing `sdk.Msg` from the JSON serialization.
> stdtx: add `Msg::from_json_value`

- stdtx/src/amino_types.rs
- stdtx/src/builder.rs
- stdtx/src/msg.rs
Simplifies construction of `StdTx` Amino messages
> stdtx: add `StdTx::new` method

- secrecy/src/lib.rs
Adds a `fmt::Formatter` argument to `DebugSecret::debug_secret`, making it into a full-fledged equivalent of `Debug::fmt`, but without a `&self` parameter which thereby ensures that there is no way to expose the underlying secret value.
This makes it possible to change the default impl to use the recently added `any::type_name` in order to display the *type* of the secret in the debug message.
> secrecy: have `DebugSecret` take a formatter

- secrecy/src/lib.rs
> secrecy: impl From for Secret

- Cargo.lock
- zeroize/derive/CHANGES.md
- zeroize/derive/Cargo.toml
- zeroize/derive/src/lib.rs
- Add docs for the `Zeroize` proc macro ([#504])
[#504]: https://github.com/iqlusioninc/crates/pull/504
> zeroize_derive v1.0.1

- Cargo.lock
- zeroize/CHANGES.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Add `doc_cfg`([#505])
- zeroize entire capacity of `String`([#352])
- zeroize entire capacity of `Vec` ([#341])
[#505]: https://github.com/iqlusioninc/crates/pull/505
[#352]: https://github.com/iqlusioninc/crates/pull/352
[#341]: https://github.com/iqlusioninc/crates/pull/341
> zeroize 1.1.1

- Cargo.lock
- datadog/Cargo.toml
- datadog/src/lib.rs
Enables Pagerduty integration. 
https://docs.datadoghq.com/api/latest/events/#post-an-event
> datadog: post StreamEvent 

- .github/workflows/rust.yml
> Fix codecov

- README.md
- anomaly/README.md
- bip32/README.md
- canonical-path/README.md
- datadog/README.md
- harp/README.md
- hkd32/README.md
- secrecy/README.md
- stdtx/README.md
- subtle-encoding/README.md
- tai64/README.md
- zeroize/README.md
- zeroize/derive/README.md
- zeroize/src/lib.rs
- Bump MSRV badges
- Remove Gitter badges
- Update copyright info
> README.md(s): various updates

- .github/workflows/zeroize.yml
> CI: build `zeroize` on ARM embedded

- zeroize/src/lib.rs
Always perform a first pass which writes zero to the entirety of an `Option`s size to ensure any residual data in the Option is cleared.
This is useful if `Some` value is moved out of the option, making a copy and setting the `Option` to `None`, but leaving data in memory.
Closes #671.
> zeroize: clear residual space within Option

- .github/workflows/iqhttp.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- iqhttp/Cargo.toml
- iqhttp/LICENSE-APACHE
- iqhttp/LICENSE-MIT
- iqhttp/README.md
- iqhttp/src/error.rs
- iqhttp/src/https_client.rs
- iqhttp/src/lib.rs
- iqhttp/src/query.rs
This is an extraction of the boilerplate we have for wiring up:
- `hyper`
- `hyper-rustls`
- `hyper-proxy`
- `serde`
- `serde_json`
The code is a refactored extraction from Delphi's `HttpsClient`:
https://github.com/iqlusioninc/delphi/blob/6e8d736/src/https_client.rs
It could probably do with a lot more refactoring along with expanded tests and types, however having any crate at all when there are multiple consumers is better than copying around boilerplate.
> iqhttp crate

- .github/workflows/mintscan.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- mintscan/Cargo.toml
- mintscan/LICENSE-APACHE
- mintscan/LICENSE-MIT
- mintscan/README.md
- mintscan/src/coin.rs
- mintscan/src/deserializers.rs
- mintscan/src/lib.rs
- mintscan/src/v1.rs
- mintscan/src/v1/staking.rs
- mintscan/src/v1/staking/validator.rs
- mintscan/src/v1/staking/validator/uptime.rs
- mintscan/src/v1/status.rs
- mintscan/tests/integration.rs
API client for the Mintscan block explorer.
Supports the following endpoints:
- `/v1/status`: chain status
- `/v1/staking/validator`: validator info
- `/v1/staking/validator/uptime`: validator uptime info
Integration tested against the live API.
> mintscan crate

- Cargo.lock
- iqhttp/CHANGELOG.md
- iqhttp/Cargo.toml
- iqhttp/src/lib.rs
- mintscan/Cargo.toml
> iqhttp v0.0.1

- Cargo.lock
- mintscan/CHANGELOG.md
- mintscan/Cargo.toml
- mintscan/src/lib.rs
> mintscan 0.0.1

- Cargo.lock
- iqhttp/CHANGELOG.md
- iqhttp/Cargo.toml
- iqhttp/src/lib.rs
- mintscan/Cargo.toml
> iqhttp v0.1.0

- bip32/README.md
> bip32: add diagram to README.md

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- hkd32/Cargo.toml
> bip32 v0.1.0

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- bip32/src/lib.rs
- Documentation improvements and usage example ([#764])
[#764]: https://github.com/iqlusioninc/crates/pull/764
> bip32 v0.1.1

- Cargo.lock
- signatory/Cargo.toml
- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/error.rs
- signatory/src/key/ring.rs
- signatory/src/lib.rs
Mostly PoC code here, no tests yet
> signatory: support for loading keys into keyrings

- signatory/src/ecdsa/keyring.rs
- signatory/src/ecdsa/secp256k1.rs
- signatory/src/error.rs
- signatory/src/key.rs
- signatory/src/key/handle.rs
- signatory/src/key/ring.rs
- signatory/src/key/store/fs.rs
- signatory/src/lib.rs
- signatory/tests/fs.rs
Also adds a `KeyHandle` enum which abstracts over the key's algorithm.
> Finish spiking out ECDSA/secp256k1 support + integration test

- Cargo.lock
- zeroize/CHANGELOG.md
- zeroize/Cargo.toml
- zeroize/src/lib.rs
- Implement Zeroize for `[MaybeUninit<Z>]` ([#793])
[#793]: https://github.com/iqlusioninc/crates/pull/793
> zeroize v1.4.1

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- signatory/src/lib.rs
- `Algorithm::EcdsaNistP256` and `Algorithm::Ed25519` variants ([#817])
[#817]: https://github.com/iqlusioninc/crates/pull/817
> signatory v0.23.1

- canonical-path/src/lib.rs
This lint is breaking the build
> canonical-path: fix tests

- Cargo.lock
- zeroize/CHANGELOG.md
- zeroize/Cargo.toml
- zeroize/LICENSE-MIT
- zeroize/derive/LICENSE-MIT
- zeroize/src/lib.rs
- Derive `Default` on `Zeroizing` ([#870])
[#870]: https://github.com/iqlusioninc/crates/pull/870
> zeroize v1.4.2

- zeroize/derive/src/lib.rs
- zeroize/tests/zeroize_derive.rs
If any more tests are desired feel free to hit me up.
Fixes #899 and #651.
> Implement `#[zeroize(skip)]`

- hkd32/Cargo.toml
- hkd32/src/lib.rs
> Add impl for std::error::Error

- bip32/src/child_number.rs
Something bitcoin core is adding: https://github.com/bitcoin/bitcoin/pull/26076
> Add ability to parse for hardened paths signaled by 'h'

- Cargo.lock
- signatory/CHANGELOG.md
- signatory/Cargo.toml
- Bump `ed25519-dalek` to v2.0 ([#1167])
[#1167]: https://github.com/iqlusioninc/crates/pull/1167
> signatory v0.27.1

- .cargo/audit.toml
- .github/workflows/security_audit.yml
Remove legacy ignores and add new ones to fix the build
> .cargo/audit.toml: fix audit

- Cargo.lock
- bip32/CHANGELOG.md
- bip32/Cargo.toml
- `PrivateKey::derive_tweak()` and `PublicKey::derive_tweak()` ([#1186])
[#1186]: https://github.com/iqlusioninc/crates/pull/1186
> bip32 v0.5.2

- Cargo.lock
- secrecy/CHANGELOG.md
- secrecy/Cargo.toml
- Impl `Deserialize` for `SecretString` ([#1220])
[#1220]: https://github.com/iqlusioninc/crates/pull/1220
> secrecy v0.10.2

- .github/workflows/workspace.yml
- secrecy/src/lib.rs
> Bump clippy to Rust 1.81

- secrecy/src/lib.rs
> secrecy: impl `Default` for `SecretString`

- secrecy/src/lib.rs
> secrecy: impl `From<&str>` for `SecretString`

- secrecy/README.md
Update README.md to remove reference to old `Secret<T>`
> Update lingering reference to Secret<T>

- bip32/CHANGELOG.md
> bip32: add CHANGELOG.md entry for v0.5.3
